### ISSUE TITLE
makejvf で作る VF（ご参考）

### ISSUE THREAD

**Issue by aminophen** [abenori/jlreq#10]
issue ではないのですが，(u)pTeX 用 VF の make についてです。

texjporg/tex-jp-build#19 で改良を続けている makejvf enhanced mode (version 20170717, [r44827](https://www.tug.org/svn/texlive?view=revision&revision=44827)) を，jlreq の make に使ってみました。結果，

- normal mode
- enhanced mode（Makefile で makejvf に `-e` オプションを追加）

で VF ファイルが一致しません。具体的には U+00AB, U+00BB の MOVERIGHT 量が違っていて，おそらく enhanced mode の結果が「正しい」ものと思われます。

~~~~
Binary files normal/ubjlreq-v.vf and enhanced/ubjlreq-v.vf differ
Binary files normal/ubjlreq.vf and enhanced/ubjlreq.vf differ
Binary files normal/ubjlreqg-v.vf and enhanced/ubjlreqg-v.vf differ
Binary files normal/ubjlreqg.vf and enhanced/ubjlreqg.vf differ
Binary files normal/ubzjlreq-v.vf and enhanced/ubzjlreq-v.vf differ
Binary files normal/ubzjlreq.vf and enhanced/ubzjlreq.vf differ
Binary files normal/ubzjlreqg-v.vf and enhanced/ubzjlreqg-v.vf differ
Binary files normal/ubzjlreqg.vf and enhanced/ubzjlreqg.vf differ
Binary files normal/ujlreq-v.vf and enhanced/ujlreq-v.vf differ
Binary files normal/ujlreq.vf and enhanced/ujlreq.vf differ
Binary files normal/ujlreqg-v.vf and enhanced/ujlreqg-v.vf differ
Binary files normal/ujlreqg.vf and enhanced/ujlreqg.vf differ
Binary files normal/uzjlreq-v.vf and enhanced/uzjlreq-v.vf differ
Binary files normal/uzjlreq.vf and enhanced/uzjlreq.vf differ
Binary files normal/uzjlreqg-v.vf and enhanced/uzjlreqg-v.vf differ
Binary files normal/uzjlreqg.vf and enhanced/uzjlreqg.vf differ
~~~~

normal mode / enhanced mode 双方で作った VF を使って dvipdfmx した PDF を添付しておきます。

[20170717-jlreq-makejvf.zip](https://github.com/abenori/jlreq/files/1151522/20170717-jlreq-makejvf.zip)

次のリリース時には `-e` 付きで makejvf していただくと良いのでは？というご参考まで。

**Comment by aminophen** [comment]
> 次のリリース時には -e 付きで makejvf していただくと良いのでは？というご参考まで。

どうやら makejvf/write.c で U+00AB と U+00BB（どちらも JIS X 0213 に含まれる）への対処が抜けているだけのようなので，version 20170731 (r44928) で `-e` なしの makejvf でも大丈夫なようにしました。

**Comment by abenori** [comment]
とりあえずそのままにしておきます
