### ISSUE TITLE
book と tate を同時に指定すると footnote に hyperref によるリンクがなくなる

### ISSUE THREAD

**Issue by ktrxcmsn** [abenori/jlreq#103]
`book` と `tate` オプションを同時に指定すると、footnote に hyperref によるリンクがなくなりました。
`report` を指定するなど、同時に指定しない場合は hyperref によるリンクが有効になりました。
たとえば下記例ではリンクがなくなってしまいます。

```latex
\documentclass[lualatex, book, tate]{jlreq}
\usepackage{hyperref}
\begin{document}
\footnote{}
\end{document}
```

**Comment by abenori** [comment]
これは想定通りです．もう少し言うと，対処仕切れなそうなので諦めました．リンクを有効にする手段は https://github.com/abenori/jlreq/issues/64 にありますのでそちらを参照してください．
