### ISSUE TITLE
running_head と running_head_ii の出力

### ISSUE THREAD

**Issue by ktrxcmsn** [abenori/jlreq#104]
以下のソースから lualatex で pdf を出力したところ

1. `running_head` と `running_head_ii` で柱の出力が異なります。
2. 9行目（`even_running_head_ii=_subsection`）をコメントインすると、1ページ目の `running_head_ii` が消えて、3ページ目の `running_head_ii` が前の節の柱に変わりました。

いずれのケースも `_subsection` を `あいうえお` などにした場合とも出力の方針が一致していないように思います。
意図された動作でしたらすみません。

```latex
\documentclass[lualatex]{jlreq}

\ModifyPageStyle{plain}{
  yoko,
  running_head_position=top-left,
  odd_running_head=_subsection,
  running_head_ii_position=top-right,
  odd_running_head_ii=_subsection,
  % even_running_head_ii=_subsection,
}
\pagestyle{plain}

\begin{document}
\section{section 1}
\subsection{subsection 1.1}
\clearpage
あ
\clearpage
\section{section 2}
\subsection{subsection 2.1}
\end{document}
```

LuaLatex: LuaHBTeX 1.13.2 (TeX Live 2021)
jlreq: 2021/11/05

**Comment by abenori** [comment]
> `running_head` と `running_head_ii` で柱の出力が異なります。

これは例えば3ページ目に`running_head`の中身が出ていないが`running_head_ii`の中身が出ていることを指しているのかと思います．

とりあえず現在の動きを書いてみます．現在生成されるページスタイルでは，`running_head`として現れる見出しの中で最も高位のもの（この場合は`\subsection`）よりも高位の見出しが現れた場合，柱をリセットする処理を行います．今の場合より高位の`\section`があるため，この段階で中身が空になります．ただ，この処理は`running_head_ii`に対しては行われていないようで，そのため`running_head_ii`の中身はそのまま出力されます．

後者はバグだと思うので直します．

**Comment by abenori** [comment]
なおしたつもりです． 6c273d8
