### ISSUE TITLE
改行に伴う和文と欧文などのアキ

### ISSUE THREAD

**Issue by Yarakashi-Kikohshi** [abenori/jlreq#106]
# 改行に伴う和文と欧文などのアキ

これはバグレポートやリクエストではありません．
質問です．

和文中で以下のようなものを行を分けながら書いた場合，アキが異なる結果を受けてしまいました．

- 欧文
- アラビア数字
- 行内数式
- siunitx による単位付きの数値

## 例

サンプルとして上から順に，

1. 改行しないもの
2. 和文以外のものを別行にしたもの
3. 和文以外のものを別行にして行末に`%` を付けたもの

としています．

<details>
<summary>すべての画像のソース (折りたたみ)</summary>
<div>

```latex
\documentclass[12pt,a5paper]{jlreq}
\usepackage{luatexja}
\usepackage{siunitx}
\usepackage[active,tightpage]{preview}
\begin{document}

\begin{preview}
  吾輩は猫である。名前はまだない。

  吾輩は
  猫
  である。名前はまだない。

  吾輩は%
  猫%
  である。名前はまだない。
\end{preview}

\begin{preview}
  三菱UFJ銀行

  三菱
  UFJ
  銀行

  三菱%
  UFJ%
  銀行
\end{preview}

\begin{preview}
  今年は2022年です！

  今年は
  2022
  年です！

  今年は%
  2022%
  年です！
\end{preview}

\begin{preview}
  光速度$c$はとても速い！

  光速度
  $c$
  はとても速い！

  光速度%
  $c$%
  はとても速い！
\end{preview}

\begin{preview}
  富士山の標高は\SI{3776}{m}です！

  富士山の標高は
  \SI{3776}{m}
  です！

  富士山の標高は%
  \SI{3776}{m}%
  です！
\end{preview}

\end{document}
```

</div></details>

### 和文

和文のみであれば，改行前後でのアキに変化はありません．（そもそもアキがない）

```latex
吾輩は猫である。名前はまだない。

吾輩は
猫
である。名前はまだない。

吾輩は%
猫%
である。名前はまだない。
```

![solidSetting-up-image-1](https://user-images.githubusercontent.com/75878492/148626995-cbfd4629-cbf6-44d4-a4fc-7e3a50a4fb36.png)

和文以外のものの場合，2番目の改行して行末に`%` を付けていないもののアキが，他2つと異なるものとなりました．

### 欧文

```latex
三菱UFJ銀行

三菱
UFJ
銀行

三菱%
UFJ%
銀行
```

![solidSetting-up-image-2](https://user-images.githubusercontent.com/75878492/148626997-246d1936-b8d1-4e18-a445-ff1c15885287.png)

2番目だけ欧文後のアキが広い．

### アラビア数字

```latex
今年は2022年です！

今年は
2022
年です！

今年は%
2022%
年です！
```

![solidSetting-up-image-3](https://user-images.githubusercontent.com/75878492/148626999-eaa455b2-0955-4b76-a3ec-13e0865ca14f.png)

2番目だけアラビア数字後のアキが広い．

### 行内数式

```latex
光速度$c$はとても速い！

光速度
$c$
はとても速い！

光速度%
$c$%
はとても速い！
```

![solidSetting-up-image-4](https://user-images.githubusercontent.com/75878492/148627000-4f0eae62-7e4b-464e-9033-fc60d006b5c9.png)

2番目だけ行内数式の後のアキが広い

### siunitx を利用した単位付きの数値

```latex
富士山の標高は\SI{3776}{m}です！

富士山の標高は
\SI{3776}{m}
です！

富士山の標高は%
\SI{3776}{m}%
です！
```

2番目だけ数値の後のアキが広い

![solidSetting-up-image-5](https://user-images.githubusercontent.com/75878492/148627002-ec484642-4ba6-479f-b51f-5fe72c394c2a.png)

## 疑問点

これらの挙動は期待された正しい挙動ですか？
また，正しい挙動の場合，どの書き方が正しい書き方になりますか？

改行に伴うアキの変化について調べてみても特に記述を見つけられなかったため，これらの挙動が期待されている正しいものなのか分かりませんでした．

**Comment by abenori** [comment]
これはpTeXの一般的な挙動です．以下のルールで説明できます．

* 和文文字と欧文文字の間には和欧文間空白（いわゆる`xkanjiskip`）が入る．ただし，数式は欧文文字であり，スペース（いわゆる半角空白）は和文文字でも欧文文字でもない．
* 和文文字の直後の改行は無視される．それ以外の改行はスペースと同様の扱い．
* コメントアウトは改行もコメントアウトする．

これらから，

```
三菱UFJ銀行

三菱
UFJ
銀行

三菱%
UFJ%
銀行
```
の二つ目は
```
三菱UFJ 銀行
```
と同じになり，UFJの後にはスペースが入ることによりその分のアキが入り，和欧文間空白は入りません．また三つ目はコメントアウトの効果により一つ目と同じになり，UFJの前後どちらも和欧文間空白が入ります．

どれが正しい記述かは結局どの空白を入れたいかによるのですが，個人的には和欧文間空白を入れるべきだと思うのでどの場合も一つ目か三つ目（この二つは等価）で記述しています．

**Comment by Yarakashi-Kikohshi** [comment]
とても分かりやすい説明をありがとうございます！
和文以外を別行にする場合は行末に`%` を付けるように心がけていきたいと思います:smile:

**Comment by Yarakashi-Kikohshi** [comment]
@abenori 
一度閉じてしまいましたが，もう一つだけアキに関して教えてください．

# 相互参照のアキ

一般的に相互参照では，`\ref` と`式` などの参照タイプは改行されるべきではないとされているようです．
そのため，次のように運用します．

```latex
式~\ref{eq:label}
```

しかしながら，`~` では半角スペースを挿入したときと同じだけのアキが生じてしまいます．

```latex
\begin{equation}
f(x) = ax^2+bx+c \label{eq:label}
\end{equation}

式1は

式\ref{eq:label}は

式~\ref{eq:label}は
```

![solidSetting-up-image-7](https://user-images.githubusercontent.com/75878492/148644721-0432f9e6-d702-466f-9843-193d11e4a70e.png)


`式` と`\ref` の間での改行を禁止しつつ，xkanjiskip の恩恵を受ける方法はありますか？

**Comment by abenori** [comment]
`あ\nobreak a`とすると分割を禁止しつつxkanjiskipが挿入されるようです．

**Comment by Yarakashi-Kikohshi** [comment]
実現出来ました．
ありがとうございます！
