### ISSUE TITLE
機能リクエスト：参考文献をToCに表示可能にする

### ISSUE THREAD

**Issue by aont** [abenori/jlreq#108]
参考文献が
https://github.com/abenori/jlreq/blob/4d9a05e847d8ec1449a6e2bd274301d3469ec537/jlreq.cls#L5522
によって```\section*{}```となっていますが，目次に表示できるように```\section{}```に変更可能にするオプションがあるとありがたいなと思いました。

**Comment by abenori** [comment]
試しに
```
\jlreqsetup{
  theindex_heading = {\section{\refname}}
}
```
とできるようにしてみました． df2d437
