### ISSUE TITLE
jlreq-trimmarks: 読み込み時のエラー

### ISSUE THREAD

**Issue by fabon-f** [abenori/jlreq#110]
最新のTeX Liveで実行すると、最小限のコードでもエラーが出ます。
バージョンはjlreqが2022/04/11、jlreq-trimmarksが2021/11/05です。

```tex
% min.tex
\documentclass[dvipdfmx,uplatex,paper=a4]{jlreq}
\usepackage[dvipdfmx,uplatex]{jlreq-trimmarks}
\begin{document}
  hoge
\end{document}
```

```
uplatex min.tex
```

```
! You can't use `\unless' before `macro'.
<to be read again> 
                   \ifjlreq@trimmarks@tate 
l.898 ...\jlreq@trimmarks@bleedboxsize@odd{\@tempa
                                                  }
```

dvipdfmx/uplatexオプションを適切に変えてplatexやLuaLaTeXで実行しても同じエラーが出ます。

jlreqやjlreq-trimmarksの問題なのか分かりませんが……(私の使い方が根本的に間違っているのでしょうか?)

**Comment by fabon-f** [comment]
環境はMacのBasicTeXで、collection-langjapaneseやその他の必要パッケージを随時手でインストールしています。

**Comment by abenori** [comment]
ありがとうございます．`\legacy_if`に入れているものがおかしいですね．今まで動いていたのがむしろ不思議です．
[902e8fa](https://github.com/abenori/jlreq/commit/902e8fac3fe3df98f583ff8d9bfd7585452db6bc) で修正しました．
