### ISSUE TITLE
epigraph パッケージとの \clearto(even|odd)page コマンドの衝突

### ISSUE THREAD

**Issue by annnagatsuki** [abenori/jlreq#111]
エピグラフを実装しようとすると、最小限のコードでもエラーが出ます。環境は次の通りです：
* macOS Monterey 12.4
* TeX Live 2022
* jlreq (2022/07/13)

```tex
%test.tex
\documentclass{jlreq}
\usepackage{epigraph}
\begin{document}
\epigraph{}{}
\end{document}
```

```
lualatex test.tex
```

```
! LaTeX Error: Command \cleartoevenpage already defined.
               Or name \end... illegal, see p.192 of the manual.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.22   \ifodd\c@page\hbox{}#1\clearpage\fi}
```

**Comment by abenori** [comment]
`\cleartoevenpage`と`\cleartooddpage`を削除しました．[a181dcb](https://github.com/abenori/jlreq/commit/a181dcb4792882a55aa2341ab05bbc197ff69ab1)

**Comment by annnagatsuki** [comment]
ご対応いただきありがとうございます。
たしかに `epigraph` パッケージが動くようになるのですが、本文中の行間と明らかに異なったもの（自分の環境では狭くなったもの）になってしまいます。これには何か対処法がありますか。

**Comment by abenori** [comment]
簡単な例をもらってもよいでしょうか？

**Comment by annnagatsuki** [comment]
今見返すと、そこまで気にしなくてもいい気がしてきました。

```tex
\documentclass{jlreq}
\usepackage{epigraph}

\begin{document}
\epigraph{行く川のながれは絶えずして、しかも本の水にあらず。よどみに浮ぶうたかたは、かつ消えかつ結びて久しくとゞまることなし。世の中にある人とすみかと、またかくの如し。玉しきの都の中にむねをならべいらかをあらそへる、たかきいやしき人のすまひは、代々を經て盡きせぬものなれど、これをまことかと尋ぬれば、昔ありし家はまれなり。}{鴨長明『方丈記』}

行く川のながれは絶えずして、しかも本の水にあらず。よどみに浮ぶうたかたは、かつ消えかつ結びて久しくとゞまることなし。世の中にある人とすみかと、またかくの如し。玉しきの都の中にむねをならべいらかをあらそへる、たかきいやしき人のすまひは、代々を經て盡きせぬものなれど、これをまことかと尋ぬれば、昔ありし家はまれなり。
\end{document}
```

<img width="748" alt="epigraph in jlreq" src="https://user-images.githubusercontent.com/88917119/182547203-c20a9b1b-af9b-4670-9c37-e61b8f08c56a.png">

**Comment by munepi** [comment]
> 本文中の行間と明らかに異なったもの（自分の環境では狭くなったもの）になってしまいます。これには何か対処法がありますか。

これはもはやjlreqと無関係な質問ですが、これに対して、

```
\renewcommand{\epigraphsize}{\normalsize}
```

とすれば良さそうなことは、epigraph.styの中身、もしくは、epigraphパッケージのドキュメントにも書かれています。

**Comment by annnagatsuki** [comment]
たしかにそうでした、すみません。BXjscls だとこの種の問題が発生しなかった気がしたので勘違いしていました。ありがとうございます。
