### ISSUE TITLE
listingsパッケージのtitleオプションでエラーになる

### ISSUE THREAD

**Issue by fabon-f** [abenori/jlreq#112]
listingsパッケージとjlreqクラスのどちらの問題か分からなかったので、とりあえずこちらでissueを立てます。

# 問題

listingsパッケージでtitleオプションを使うと、エラーが出ます。

(`@makecaption`周辺のエラーのようですが……)

# 再現用コード
```tex
\documentclass[dvipdfmx]{jlreq}
\usepackage{listings}

\begin{document}

\begin{lstlisting}[title=hoge,language={tex}]
\LaTeX
\end{lstlisting}

\end{document}
```

# 結果
```
! Argument of \lst@title@dropdelim has an extra }.
```

(dvipdfmxオプションを削除してLuaLaTeXで実行しても同じエラーで止まりました)

**Comment by abenori** [comment]
とりあえず 6e75b54 でエラーが出ないようにしました．ただこれはlistingsの方がいまいちという気もしますねぇ．（  `\@makecaption` が特定の形で実装されていることに依存している．）
