### ISSUE TITLE
柱の番号がずれる

### ISSUE THREAD

**Issue by kyoHashimoto** [abenori/jlreq#113]
以下のコードをコンパイルすると，できあがったPDFの3ページ目の柱が「1.5　5段落」と表示されてほしいところ，「1.4　4段落」になってしまいました．

```[LaTeX]
\documentclass[%
book,a5paper
]{jlreq}%

\NewPageStyle{mypagestyle}{
  running_head_font=\sffamily\footnotesize,
  running_head_position=top-fore-edge,
  nombre_font=\sffamily\bfseries,
  nombre_position=top-fore-edge,
  odd_running_head=_section,
  even_running_head=_chapter,
  mark_format={_section={\thesection\quad #1},
    _chapter={第\thechapter 章\quad #1}}
}

\SetBlockHeadingSpaces{
  [lines=4]{_section,12pt,_subsection,9pt}
}

\pagestyle{mypagestyle}

\usepackage{bxjalipsum}

\begin{document}

\chapter{吾輩は猫である}

\section{1段落}

\jalipsum[1]{wagahai}

\section{2段落}

\jalipsum[2]{wagahai}

\section{3段落}

\subsection{3-1段落}

\jalipsum[3]{wagahai}

\section{4段落}

\jalipsum[4]{wagahai}

\section{5段落}

\subsection{5-1段落}

\jalipsum[5]{wagahai}

\section{6段落}

\end{document}
```

![image](https://user-images.githubusercontent.com/11057300/186382778-f11aa9cf-9a20-4993-9ad8-86d6b2e0e6e1.png)

\SetBlockHeadingSpacesを消すと正しく表示されるのですが，当然ながら行取りが設定できません．
対処法があれば教えていただけますと幸いです．

なお，こちらのTeX環境は以下のとおりです，

This is LuaHBTeX, Version 1.15.0 (TeX Live 2022) 
 restricted system commands enabled.
(./main.tex
LaTeX2e <2022-06-01> patch level 5
 L3 programming layer <2022-07-15>
(c:/texlive/2022/texmf-dist/tex/latex/jlreq/jlreq.cls
Document Class: jlreq 2022/07/13 jlreq

**Comment by abenori** [comment]
ありがとうございます．バグってますね．直します．`SetBlockHeadingSpaces`の効力が発動すると柱への追加が行われないようになっているようです．

**Comment by abenori** [comment]
[9acb871](https://github.com/abenori/jlreq/commit/9acb87172e565f0fbbd00abd6fda7e6e5dea8604)で正常になるかと思います．

**Comment by kyoHashimoto** [comment]
ありがとうございます．確認できました．
