### ISSUE TITLE
ISO C4 用紙サイズ誤り

### ISSUE THREAD

**Issue by aminophen** [abenori/jlreq#114]
ISO C4 用紙サイズが間違っています。「229×354」→「229×324」が正

https://github.com/abenori/jlreq/blob/bdcde95937a1a5268f2db834d4f9fdcdc4fd52eb/jlreq-helpers.sty#L444

原因：恐らく libpaper を参考になさったと思います。libpaper の間違いはかなり古く，少なくとも 2004 年のバージョン 1.1.14 には見られます。2018 年にバージョン 1.1.25 で直されました。TeX Live でも dvipdfmx と psutils が libpaper に依存していますが，長らく間違ったバージョン 1.1.24 を使ってきましたが，本日 1.1.28 に更新しました。 [r64327](https://www.tug.org/svn/texlive?view=revision&revision=64327)

**Comment by abenori** [comment]
ありがとうございます．直しました． [3a4bc17](https://github.com/abenori/jlreq/commit/3a4bc17db0042b9d7a79f2a8f5de5e0b943110ad)
