### ISSUE TITLE
jlreq-trimmarksとjlreqクラスオプションbook, twosideの組合せによるエラー

### ISSUE THREAD

**Issue by yuni-hutsuka** [abenori/jlreq#119]
jlreqのクラスオプションにbookを指定した時、jlreq-trimmarksを同時に使用していると、次のようなエラーメッセージが表示されます。

```latex
\documentclass[
    book
]{jlreq}

\usepackage{jlreq-trimmarks}

\begin{document}
テスト文章
\end{document}
```

```
! Missing number, treated as zero.
<to be read again>
)
l.960 ...f\jlreq@trimmarks@bleedboxsize@even{\@tempa
                                                  }%
?
```

実際にエラーを発生させたソースについてはあまりに冗長が過ぎるので省きますが、いくつかクラスオプションの組合せを試してみたところ、おそらくbook, twosideの2オプションを使用した際に発生するエラーのようです。

あるいは、これを回避する方策などがあればご教授願えればと思います。

**Comment by abenori** [comment]
確かに`tate`でアウトでした．謎の括弧があったので消しました． 5800548

**Comment by yuni-hutsuka** [comment]
お返事が遅くなり誠に申し訳ありません。
ご対応いただき本当にありがとうございます。
