### ISSUE TITLE
lualatex利用時にeveryhookを要求される

### ISSUE THREAD

**Issue by sh9temp** [abenori/jlreq#120]
https://github.com/abenori/jlreq/blob/289365c7ef0ab69cddd81af0dbe6b8036d17d483/README-ja.md?plain=1#L19-L24
とありますが
https://github.com/abenori/jlreq/blob/289365c7ef0ab69cddd81af0dbe6b8036d17d483/jlreq.cls#L2229
によりエラーになります。
```tex
\ifx l\jlreq@engine
...
\else
```
が欠けているかドキュメントが追随できていないと思われます。

**Comment by abenori** [comment]
ありがとうございます．多分LaTeXのHookでよいと思うのでそちらで代用しました．[7fb1db3](https://github.com/abenori/jlreq/commit/7fb1db368f509e683c176ea679789df1f9361101)

**Comment by sh9temp** [comment]
多分直っていません。最小限の、everyhookを入れるとコンパイルできて入れないとコンパイルできない環境を作れました（lualatexではeveryhookをrequireしていないのにeveryhookの制御綴りを無事に呼び出せていて変ですが。かといってeveryhook無しでもeveryhookの制御綴りに到達するまでエラーが出ないのでrequireを通っているわけでもないようです）
そして修正内容的に非lualatex環境での動作に問題が出そうです（当方ptex系環境未経験の為確かめられず）

**Comment by abenori** [comment]
肝心のところを消し忘れました．[749c31a](https://github.com/abenori/jlreq/commit/749c31afc4488457f3a1e13e643b9003772301a9)

**Comment by sh9temp** [comment]
ありがとうございました。
