### ISSUE TITLE
同行見出し後に箇条書き前の空きが入らない

### ISSUE THREAD

**Issue by Physics-Ludus** [abenori/jlreq#121]
```\section``` 直下に同行見出しを置き，その下に箇条書きを入れると箇条書き前のスペースがなくなります．

```\section``` と同行見出しの間に1文字でも入っていれば箇条書き前に適切にスペースが入ることは確認しました．
同様の事例を```\subsection```でも確認しました．

```tex
\documentclass{jlreq}

\NewRuninHeading{dougyou}{4}{}
\jlreqsetup{itemization_beforeafter_space={50pt}}

\begin{document}

\section{別行見出し}
\dougyou{同行見出し}
本文
\begin{enumerate}
	\item 箇条書き
\end{enumerate}
本文

\end{document}
```

**Comment by abenori** [comment]
ありがとうございます．`\@startsection`の実装を真似ました．これで大丈夫かな？[c24bb77](https://github.com/abenori/jlreq/commit/c24bb77887ad815f686c154dad5840dff468e7cc)

**Comment by Physics-Ludus** [comment]
スペース入ってました．ありがとうございます．
