### ISSUE TITLE
\tableofcontents で二段組みを解除しないオプション（あるいは段数を含め目次の版面を調整できるオプション）があると助かります

### ISSUE THREAD

**Issue by lemniscati** [abenori/jlreq#124]
現行の jlreq.cls ですと，二段組設定の場合には \tableofcontents の展開時に強制的に段組みなしに変更されてしまいます．
https://github.com/abenori/jlreq/blob/4ff954fe6e8f7e11c10a01f630b3658b00c991ca/jlreq.cls#L5725-L5736

この設定をキャンセルできるオプションか，あるいは段数を含め目次の版面を調整できるオプションがあると助かります．

いかがでしょうか．

**Comment by abenori** [comment]
`tableofcontents_twocolumn`を`\jlreqsetup`に追加してみました． [45837f6](https://github.com/abenori/jlreq/commit/45837f6de41c160c83aa0c9b27de4a33bc99b797)

**Comment by lemniscati** [comment]
早速のご対応ありがとうございます．

`\if@restonecol` の名前が紛らわしくなるので（二段組みに復帰する場合もあるので），
復帰用の設定を例えば `\@restcolcmd` に保存することにして，次のようにするのはいかがでしょうか．
```latex
\newcommand{\tableofcontents}{%
  \jlreq@top@contents=-100\relax
  \if@twocolumn
    \bool_if:NTF \g__jlreq_tableofcontents_twocolumn_bool {
      \def\@restcolcmd{}% 段組設定は復帰不要
    }{
      \def\@restcolcmd{\twocolumn}% 段組設定を復帰するときは二段組
      \onecolumn
    }
  \else
    % スイッチの流用
    \bool_if:NTF \g__jlreq_tableofcontents_twocolumn_bool {
      \def\@restcolcmd{\onecolumn}% 段組設定を復帰するときは一段組
    }{
      \def\@restcolcmd{}% 段組設定は復帰不要
    }
  \fi
  \prop_item:Nn \g__jlreq_tableofcontents_prop { heading }
  \@mkboth{\contentsname}{\contentsname}%
  \@starttoc{toc}%
  \@restcolcmd% 段組設定を復帰する
}
```

**Comment by lemniscati** [comment]
そのほか，以下のようにグローバルオプションに `tableofcontents_twocolumn` を書き込んだ場合は，無視されてしまいます．
これは意図的なものでしょうか．
```latex
\documentclass[
  tableofcontents_twocolumn,
]{jlreq}
```

もちろん，`\jlreqsetup` を使えばちゃんと認識されます．
```latex
\documentclass{jlreq}
\jlreqsetup{
  tableofcontents_twocolumn,
}
```

**Comment by abenori** [comment]
`\jlreqsetup`で指定できるのでクラスオプションによる指定はできません．（これは他のオプションも同様．）

**Comment by lemniscati** [comment]
了解しました．よく分かっておらず失礼しました．

このオプション `tableofcontents_twocolumn` があると，目次を二段組にしたいときに `\tableofcontents` を再定義しなくてすむので助かります．
ありがとうございます！
