### ISSUE TITLE
titlesecによるchapterへの変更が適用できない

### ISSUE THREAD

**Issue by annnagatsuki** [abenori/jlreq#134]
https://detail.chiebukuro.yahoo.co.jp/qa/question_detail/q14287329069 と同じ問題が発生したのですが、回答にある解決策は `\frontmatter`, `\mainmatter`, `\appendix` と相性が悪いようです（それぞれの直後に置くと解決しますが）。恐縮ですが、ご対応のほどよろしくお願い申し上げます。

**Comment by abenori** [comment]
基本的にtitlesecが標準クラスファイルなどでの見出し命令の実装に依存した形で行っているのが原因だったと思います．ではjlreqも合わせればよいのではないかというそう単純ではなく，標準クラスファイルの実装でできることは貧弱でJLReqの規定する動作の実現は難しいです．というわけで，

> 恐縮ですが、ご対応のほどよろしくお願い申し上げます。

とのことですが，現段階では諦めてください．ちなみにjlreqクラスファイル自身の持つ見出し命令の定義コマンドを使わない理由は何なのでしょうか？

**Comment by annnagatsuki** [comment]
実は，レガシーLaTeX時代の文書をそのままモダンLaTeXに移植できたら楽だと思ったのですが，仰る通り `\ModifyHeadings` などで新たに作成する方が好ましかったです．無事に移植できたので，このissueは閉じさせていただきます．ご対応いただきありがとうございます．
