### ISSUE TITLE
後続ページがsection等のheadingで始まるとき、\clearpageしないとfootnoteが版面下にならず本文直下に配置されてしまう

### ISSUE THREAD

**Issue by kmuto** [abenori/jlreq#19]
説明が難しいのですが、添付のPDFにて。

ソースは以下です。jlreqは2017/12/22、luatex 1.0.4です。
```
\documentclass{jlreq}
\begin{document}
\section{A}
content\footnote{f1}

\vspace{50\zh}

content
%\clearpage

\section{B}

content\footnote{f2}

\vspace{50\zh}

content, do clearpage
\clearpage

\section{C}

\end{document}
```
[test2.pdf](https://github.com/abenori/jlreq/files/1611966/test2.pdf)

**Comment by kmuto** [comment]
uplatexだと問題ないですね…

**Comment by abenori** [comment]
とりあえず何が起こっているかは把握しました．なんじゃこりゃ．

**Comment by yuw** [comment]
これ\raggedbottom時の素直な出力に思えます．

詳しく調べていないので記憶のみですが，pdflatexでも同様の結果になると思います．
また \section に限らず，大きめのボックスがあれば同様に脚注が上ると思います．
実際，とある欧文ジャーナル案件（pdflatex運用）ではこの問題を解決するために \footnoterule を出力するところで \vfill したこともありました．

**Comment by abenori** [comment]
> これ\raggedbottom時の素直な出力に思えます．

そういえばLuaTeX-jaはLaTeXの標準通りなのでした．eaf24d0 で`\fnfixbottomtrue`するようにしました．

**Comment by kmuto** [comment]
手元で同じのを入れてみたところ、うまくいきましたー
