### ISSUE TITLE
図表のキャプションの設定

### ISSUE THREAD

**Issue by kmaed** [abenori/jlreq#2]
まずは素晴らしいものをありがとうございます．早速自分用のデフォルトにしてみました．私は横組しか基本的に使わないので縦組はあまり試せそうにありませんが……．

このクラスファイルだけで xkeyval なインターフェースで色々カスタマイズできるのでとても便利だと思いました．一方で，一つ気になったのが図表のキャプションのフォントが `\reset@font\small\headfont` で固定で，変更するためのインターフェースが提供されていないことです．JLReq の「4.3.1 図版配置の指定方法」の注4を見ると

> キャプションは，本文の文字サイズよりは小さくし，フォントも変える場合が多い．
> ……
> キャプションのフォントを変える場合，キャプション全体をゴシック体にする方法（図 4.81の上側の例）と，図番号だけをゴシック体にする方法（図 4.81の下側の例）がある．

ということなのですが，こういった設定も簡単にできるようにならないでしょうか．

なお，caption.sty を使えば
```
\usepackage{caption}
\makeatletter
\DeclareCaptionFormat{myformat}{\reset@font\small\headfont#1\hskip1\jlreq@mol\normalfont#3}
\captionsetup{format=myformat}
\makeatother
```
とかやれば一応できているように見えるのですが，`Unsupported document class (or package) detected` と警告が出るのがいやな感じです．

**Comment by abenori** [comment]
ありがとうございます．何か気がついた点があればいろいろお願いします（って早速気がついた点を言っていただいているわけですが）．

これはできるようにしないとならないですね．

    \jlreqsetup{caption_format={\small\headfont#1 \hskip1zw#2}}

みたいにできるよにするのがよいか，

    \jlreqsetup{
        caption_font={\small\headfont},
        caption_label_font={\small\normalfont}
    }

とフォントだけ設定できれば十分なのか．JLReq的には下で十分に見えますが，上の方がより便利なのは確かかなぁ．

**Comment by kmaed** [comment]
JLReq を実装するという目的からすると，とりあえずはフォント指定があれば十分なように思います．フォーマットまで指定するのは使うことがあるのでしょうか．図番号と説明文の間のアキ量の調節ぐらい？

**Comment by abenori** [comment]
abenori_devの a078b6a で

    \jlreqsetup{
        caption_font={\small\headfont},
        caption_label_font={\small\normalfont}
    }

の形で指定できるようにしてみました．

**Comment by kmaed** [comment]
確認しました．ありがとうございました．また何かあれば書きます．
