### ISSUE TITLE
\@makecaptionへの要望

### ISSUE THREAD

**Issue by kmuto** [abenori/jlreq#20]
- 現状ではラベルがない場合（#1が空だった場合）の想定がなく、ラベルの#1を空にしても区切り記号のスペースが入ってしまいます。#1が空だった場合には区切り記号は入れないようにしてほしいです。イメージとしてはこんなかんじでしょうか。

```
\jlreq@ifempty{#1}{%
\sbox\@tempboxa{{\jlreq@@makecaption@font #2}}}{%
\sbox\@tempboxa{{\jlreq@@makecaption@label@font #1}\hskip 1\zw{\jlreq@@makecaption@font #2}}}
```

- ラベルとキャプションの区切りが`\hskip 1\zw`固定になっていますが、JLREQでは「和文1スペース」という規定はないように思います。実際の組版では「：」なども使うので、パラメータ化して変更可能になると嬉しいです。

- キャプション位置がセンターになっていますが、JLREQでの図表は確かにそういう形になっているものの、キャプション位置についての明確な規定がないように思います。実際の組版では図はともかく、表は左にすることも多いかと。makecaptionコマンドでl, c, rなどのposを[]オプション取れるようにできたりしないでしょうか。

**Comment by abenori** [comment]
早速ありがとうございます．`図1：ライオン`とかにしたければ

```
\jlreqsetup{
  caption_label_format={#1：},
  caption_after_label_space=0pt
}
```
と指定する，というので実用上足りるでしょうか？もっと柔軟には以前 #2 に書いたようなformat指定というのもありますが．

> 実際の組版では図はともかく、表は左にすることも多いかと。

実用上どのようなケースがありますか？

* 一つの文章内で表にしろ図にしろキャプション位置は統一．
* 表のキャプション，図のキャプションは文章内で統一されているが，表は左，図は中央ということもある．
* 一つの文章内でキャプションにより場所がまちまち．図1のキャプションは左だが図2は中央，というように．

三つ目だと`\caption`をオプションをとれるようにするよう拡張しないとならないので抵抗がありますが……．

**Comment by kmuto** [comment]
ありがとうございます、オプションのほうはそれでよさそうに思えます。

ケース1と2の違いを私がよく理解できなかったのですが、

- 文章全体では図グループ、表グループのそれぞれのグループにおいてキャプションの位置は一律です。ケース3はないです（それはおそらくTeXでやる文書ではない…）。
- 紙面デザインにおいて、図キャプションはセンターに置くデザインは確かに多いです。しかし、一部では左に置くデザインもあります（jsbookもそうですよね）。
- 紙面デザインにおいて、一般書では表キャプションは確かにセンターが多いものの、技術書だとたいてい左（表自体も左寄せ）です。

**Comment by abenori** [comment]
1と2の違いは「表のキャプションは左，図のキャプションは中央」が許されるかどうかでした．許される感じでしょうか．だとすると

```
\jlreqsetup{
  caption_align={figure=center,table=left}
}
```
とかいう感じでどうでしょう？

**Comment by kmuto** [comment]
ありがとうございます、横書きにはその名前でよさそうですが、こういうのは縦書きだとどうしてるんでしょう（top/bottomとかにして中で処理を転換？）。

**Comment by abenori** [comment]
あ，仰るとおりですね．top/bottomにして内部ではtop=left,bottom=rightとして扱いましょうか．

**Comment by abenori** [comment]
のんびりですが，abenori_devの 240c601 で追加しました．`caption_label_format`や`caption_after_label_space`は上の通り，`caption_align`は上のような指定か，単に`caption_align=center`（tableとfigureどちらも変更する）のように指定できるはずです．

**Comment by kmuto** [comment]
ありがとうございます、確認できました。
\@captypeを見るようになったので、プログラムコードリストキャプションなどに流用しようとすると工夫が必要そうですね。

**Comment by abenori** [comment]
listingsとかということですかね．確かにそうですね．もう少し手を加えるかもしれないです．

**Comment by abenori** [comment]
bdd0dc1 で環境名（`\@currenvir`）を見るようにしました．（もし未定義ならば`\@captype`に回していますが，まず起こらないはずです．）\jlreqsetup{caption_align={lstlisting=center}}とかでも効いてそうです．
