### ISSUE TITLE
LuaTeX で使用時の和欧文間アキが妙に広くなることがある

### ISSUE THREAD

**Issue by kmaed** [abenori/jlreq#27]
普段使いしていて気になっていたことの MWE をようやく作ってみました．原因はよくわかっていないのですが．例文には全く意味はありません．
```
\documentclass[line_length=36zw]{jlreq}
\begin{document}
コンピュータは2進数で記述された命令を理解する．
コンピュータは2進数で記述された命令を理解する．
コンピュータは2進数で記述された命令を理解する．
コンピュータは2進数で記述された命令を理解する．
\end{document}
```
これを (u)platex で処理したときと lualatex で処理したときを比較すると，出力の2行目の真ん中あたりにある「2」の前後のアキが，lualatex の場合に妙に広くなります．自分の jlreq で作成した文書を見ていると，このような箇所が結構あって気になります．

**Comment by abenori** [comment]
行の調整処理における優先度の問題化と思います．多分kanjiskipとxkanjiskipしか調整に使える場所がないと思いますが，この場合xkanjiskipが優先されるようです（JLReq: 3.8.4）．(u)platexの場合は優先順位をつけることがそもそも不可能なので均等に空きます．というわけで仕様通り（(u)platexの方が駄目）です．気になるようならば，`\ltjenableadjust[priority=false]`して優先度をつけないようにすれば(u)platexと同じになります．

**Comment by kmaed** [comment]
ありがとうございます．JLReq の該当個所を読みましたが，欧文間がなければ和欧文間を最大で二分アキまで可とするのを最優先で調整するのですね．従来の挙動に慣れていたので違和感があったのですが，仕様ということで納得しました．無知で申し訳ありませんでした．
