### ISSUE TITLE
article のときの abstract

### ISSUE THREAD

**Issue by kmaed** [abenori/jlreq#3]
article な（titlepage じゃない）ときに abstract 環境を使っても何も出力されません．\jlreq@abstractbox に飲み込ませてそのままなように見えます．

**Comment by abenori** [comment]
すみません，そもそもabstractの実装が途中やめになっていました……これは酷い．とりあえずabenori_devの bee97c9で入れましたが，二段組みの場合がまだおかしいです．

**Comment by abenori** [comment]
二段組みでも大丈夫と思います．abenori_devの 64b1b32 です．

**Comment by kmaed** [comment]
確認しました．`\maketitle` がないと abstract が出力されないのは仕様なのですね．

3056行目の

    \ifthenelse{\equal{jlreq@article@type}{book}}{}{% article,report

ですが，`jlreq@article@type` の前のバックスラッシュが抜けているせいで book の場合にも abstract 環境が定義されてしまっています．

**Comment by kmaed** [comment]
よく見ると，twocolumn で abstract → \maketitle の順にしたときに，概要が右寄せになっていて中心がずれてしまっているように見えるのですが，これは意図通りなのでしょうか？

**Comment by abenori** [comment]
> 概要が右寄せになっていて中心がずれてしまっている

これは意図してないです．後で直します．

> `\maketitle` がないと abstract が出力されないのは仕様なのですね．

悩むのですが，どうするのがいいんでしょう？昨日は，とりあえず二段組の場合に概要を二段組に組み込むが否かを選べた方がよいと思い，jsarticleと同様にしてみた→一段組でも常に概要が後に出ないと二段組と整合的ではないかなと思ったので，今の形にしてみたのですが．

**Comment by kmaed** [comment]
> 悩むのですが，どうするのがいいんでしょう？

おっしゃりたいことはよくわかりますし，私としては特にこうするべきという意見があるわけでもありません．ただ単に私が試すときに `\maketitle` を書くのをサボっていたから少し混乱したというだけの話です．

**Comment by abenori** [comment]
正直なところどうするのがよいのかさっぱりですが，とりあえず今のまま（一段組ではどっちが先でも同じ：`\maketitle`がないと概要が出ない，二段組はjsarticleに従う）できちんとしてみます．
（いろいろ悩むので，何か思うところがあればお願いします．）

**Comment by munepi** [comment]
つまるところ、clsファイルの仕様に関わることで、クラスファイルごとにお作法もアレだったりしますけれども :-) 、個人的には、 `\maketitle` で出力するタイトル部の情報（タイトルや副題、著者情報、概要、キーワードなど）は、プリアンブルのみに書けるようにしておくのが好みです。

たとえば、一般的な汎用記事クラスファイルでよくある `\title` や `\date` 、 `\author` 、 `abstract` 環境は、プリアンブルのみで記述できて、 `\begin{document}` 以降（通常、この直後に） `\maketitle` でタイトル部を出力するということです。

実際に、学会誌用クラスファイルの組版仕様により、副題 `\subtitle` やキーワード `\keyword` などがあったりなかったりで、タイトル部の出力を変えたり、タイトル部全体を行取りをしたりする場合もあります。

**Comment by abenori** [comment]
> クラスファイルごとにお作法もアレだったりしますけれども :

うぐぅ．やっぱり～？困ったモノです……．折衷案的ですが，

* プリアンブルに概要が書かれた場合は`\maketitle`で出力する
* 本文中に書いてある場合はそのまま出力する

としてみましょうかねぇ．なんか中途半端でわかりにくい気もしますが，よくある`\maketitle\begin{abstract}***\end{abstract}`でも動くようにはしておきたい．

**Comment by abenori** [comment]
ちょっと変な仕様だなぁと思いつつもプリアンブルに`abstract`環境があるかで場合分けをすることにしてみました：abenori_devの 4cd9d06
