### ISSUE TITLE
目次の節番号の幅

### ISSUE THREAD

**Issue by kmaed** [abenori/jlreq#30]
現在のデフォルトだと article でも book でも，目次において節番号が2桁になると見出しにほぼくっついて，3桁になると見出しと重なってしまうので，もう少し節番号の幅 `\@lnumwidth` を広げられないかなあ，と思っています．既に目次の調整用のインターフェースがあるようならば申し訳ありません．
```
\documentclass{jlreq}
\begin{document}
\tableofcontents
\section{あああ}
\section{あああ}
\section{あああ}
\section{あああ}
\section{あああ}
\section{あああ}
\section{あああ}
\section{あああ}
\section{あああ}
\section{あああ}
\section{あああ}
\end{document}
```

**Comment by abenori** [comment]
前から悩んでいる部分です．

`\Declare***Heading`内で自動計算しているのですが，どうするのがいいんですかねぇ．今は`floor((カウンタが9の時のラベルの長さ)/1zw) + 1zw`って感じです．

**Comment by kmaed** [comment]
桁数が2桁になる場合があることを考えると，全角の整数単位ならば `... + 2)zw` は欲しいように思います．ただ，いくつかの本（ただし数学書ばかり）の目次と比べてみるとこれだと広すぎるような気も確かにします．横組しか見ていなかったので縦組も今見てみましたが，やはり節番号と見出しがくっついちゃってますね．

「カウンタが9の時」を「カウンタが99の時」にする手もありますが，これだと book の場合にはデフォルトで現行と変わらなくて，節番号が2桁になるとくっつく一歩手前になります．章番号も2桁になると見出しにかぶってしまいます．

目次の組み方はいくつかのパターンがあるようで，このあたりも設定できるようにすると jlreq ベースでカスタマイズする場合にも便利かもしれません．一方で，これらは JLReq にあるような話ではないので，どこまでやるべきか，ということを悩まれているのだとは思います．

* ページ番号について，見出しのあと \dotfill 的なやつか，\hfill か，\hspace{*zw} か
* 節番号と見出しの間隔．大きく2パターンありそうです．

現在の jlreq や jclasses などは
```
9  見出し
10 見出し
```
な感じですが，節番号と見出しの間のアキが一定の場合
```
9  見出し
10  見出し
```
も見かけます．最近出た『数式組版』の目次も見てみたところ，章番号，節番号は
```
 9  見出し
10  見出し
```
のように右寄せで，小節番号は1つ上の「アキ一定」のようでした．

**Comment by abenori** [comment]
とりあえず自動計測でもうまく行くようにはしたいと思っていました．なんとなくいろいろ思ってみたことをだらだら書いてみます．

* +2zwとする．広すぎ？
* 切り捨てではなく四捨五入とする．上の例だと悪くなさそう．
![toc](https://user-images.githubusercontent.com/522782/39459695-57138618-4d38-11e8-83c0-9df45b904996.png)

* 文章中に表れるセクション番号の最大値を.aux経由で取得し，それを使う（やり過ぎ？）

> 一方で，これらは JLReq にあるような話ではないので，どこまでやるべきか，ということを悩まれているのだとは思います．

お見通しですね．現状のパターンはLaTeXのデフォルト（からパラメータをいじったもの）です（たぶん）．パラメータなどをいじれるようにするのは，トンボと同様に別パッケージで入れてもいいかもしれません．けどそれなら既存のtitletocパッケージでよいのかなぁ．（使ったことないけど．上記のパターンくらいは実現できるんだろうか．）

**Comment by kmaed** [comment]
> お見通しですね．

見通せているわけではなくて，以前のように仕様通りなのに要望すると失礼と思って，色々調査中に Twitter でそう書かれているのを見ました．

> 既存のtitletocパッケージ

私もこれは試したことがありませんでした．あとでどれぐらいできるのか試してみます．

**Comment by abenori** [comment]
> 以前のように仕様通りなのに要望すると失礼と思って

こちらは気にしてないので，あまり気になさらないでください．少し試してみますが，とりあえずデフォルト値は四捨五入にするあたりで手を打ってみようかと思います．`\jlreq@heading@make@l@`内の

````
      \divide\jlreq@tempdima by \jlreq@tempdimb
      \edef\jlreq@do{%
        \unexpanded{\def\jlreq@result}{%
          \noexpand\def\expandonce{\csname l@#1\endcsname}{\unexpanded{\@dottedtocline{#2}{0\zw}}{\the\numexpr\jlreq@tempdima + 1\relax\noexpand\zw}}%
        }%
      }%
````

を

````
%      \divide\jlreq@tempdima by \jlreq@tempdimb
      \edef\jlreq@do{%
        \unexpanded{\def\jlreq@result}{%
          \noexpand\def\expandonce{\csname l@#1\endcsname}{\unexpanded{\@dottedtocline{#2}{0\zw}}{\the\numexpr\numexpr\jlreq@tempdima/\jlreq@tempdimb\relax + 1\relax\noexpand\zw}}%
        }%
      }%
````

とするとそうなりますので，よければ試してみてください．

> あとでどれぐらいできるのか試してみます．

こちらも少しいじってみます．

**Comment by kmaed** [comment]
> デフォルト値は四捨五入にする

試してみたところ，自分が利用している article での目次や，tate での出力はよさげになりました．book の場合は従来通りのようで，調整の余地がまだあるかもしれません．

titletoc は明日にでも試してみます．

**Comment by abenori** [comment]
titletocはいじれていないのですが．

カウンタを99にする＆四捨五入にする，あたりで手を打ちましょうかね．これならば多くの場合に二桁でも最低半文字分は空きができます．または更に+1zwを+2zwでもよいのかもしれません．そもそも全角の自然数倍である必然性があるのかもわかりませんが……．

> ただ，いくつかの本（ただし数学書ばかり）の目次と比べてみるとこれだと広すぎるような気も確かにします．

jarticleやarticleはあまり空きがないですが，jsarticleはがっつり空いていますね．個人の好みの範疇な気もするので，とりあえずがっつり空き設定をデフォルトにしてもよいかもしれないです．（で，気に入らないならばtitletocとか何か別パッケージ使ってもらう．）

**Comment by kmaed** [comment]
明日どころではなくなってしまいましたが，ようやく titletoc を試してみました．少しTeX 力が必要ですが，どうにでも設定できそうです．便利ですね．

```latex
\documentclass{jlreq}
\usepackage{titletoc}
\makeatletter
\titlecontents{section}         % 対象の見出し命令
              [0pt]             % 左マージン（オプションのように見えるが必須）
              {}                % above-code
              {\bfseries\hbox to 2\zw{\hss\thecontentslabel}\hspace{1\zw}} % 番号付きのフォーマット
              {}                % 番号なしのフォーマット
              {\leaders\hbox{$\m@th\mkern \@dotsep mu$\null\inhibitglue ・\inhibitglue\null$\m@th\mkern \@dotsep mu$}%
               \hfill\nobreak
               \hb@xt@\@pnumwidth{\hss\normalfont\normalcolor\thecontentspage}} % ページ番号のフォーマット
\titlecontents{subsection}
              [2\zw]
              {}
              {\hbox to 2\zw{\thecontentslabel}\hspace{1\zw}}
              {}
              {\hspace{2\zw}\thecontentspage}
\makeatother
\begin{document}
\tableofcontents
\section{あああ}
\section{あああ}
\section{あああ}
\section{あああ}
\section{あああ}
\section{あああ}
\section{あああ}
\section{あああ}
\section{あああ}
\section{あああ}
\subsection{いいい}
\subsection{いいい}
\subsection{いいい}
\subsection{いいい}
\subsection{いいい}
\subsection{いいい}
\subsection{いいい}
\subsection{いいい}
\subsection{いいい}
\subsection{いいい}
\end{document}
```

**Comment by abenori** [comment]
どうもありがとうございます．こちらはまだ遊べていません……．ともかく気に入らなければパッケージでどうにかしろということにして，jlreq.clsのデフォルト値は少し（かなり？）長めにしてみました．重なっちゃうよりはましだと思うので．

> 少しTeX 力が必要ですが

TeX力を除こうとするとこんな感じでしょうか？（6ptの部分は適当です．）

````LaTeX
\titlecontents{section}[0pt]{}
    {\bfseries\makebox[2\zw][r]{\thecontentslabel}\hspace{1\zw}}{}
    {\hspace*{6pt}\titlerule*[6pt]{・}\contentspage}
````

> % 左マージン（オプションのように見えるが必須）

titlesecもそうですが，`[]`で囲まれた引数が必須ってのはどうしてこうなったんでしょうね．

**Comment by kmaed** [comment]
> jlreq.clsのデフォルト値は少し（かなり？）長めにしてみました．

確認しました．確かにちょっと長めですが，よいのではと思います．

> TeX力を除こうとするとこんな感じでしょうか？

代わりに LaTeX 力が必要になりました……．

> `[]`で囲まれた引数が必須ってのはどうしてこうなったんでしょうね．

確かなことはわかりませんが，ドキュメントには

> &lt;left&gt; even if bracketed is currently mandatory...

という記述があるので，オプションにする意思はあったけれどもそのままになってしまっている，ということではないかと思います．
