### ISSUE TITLE
同行見出しのあとに文字がないと見出しが表示されない

### ISSUE THREAD

**Issue by kmaed** [abenori/jlreq#31]
``` latex
\documentclass{jlreq}
\begin{document}
\paragraph{あああ}
%いいい
\begin{itemize}
\item ううう
\end{itemize}
\end{document}
```
のように，\paragraph のあとにいきなり itemize を置いたりすると見出しの「あああ」が表示されないのですが，これは仕様なのでしょうか（そういう使い方をするな，という批判は別にして）．「いいい」のコメントを外すとちゃんと見出しも表示されます．

**Comment by abenori** [comment]
ありゃ，バグってますね．\@startsectionをまねていたつもりだったのですが，どっかで失敗しているみたいです．

**Comment by abenori** [comment]
masterの 0b4cfb2 で直しました．

**Comment by kmaed** [comment]
確認しました．ありがとうございます！

**Comment by kmaed** [comment]
まだおかしな挙動がありました．次のように \paragraph 直後に equation を入れると，そのあとの改段落後に再び \paragraph の見出しが現れます．

``` latex
\documentclass{jlreq}
\begin{document}
\paragraph{あああ}
\begin{equation}
  a
\end{equation}

いいい % なぜかこの前に「あああ」が入る
\end{document}
```

**Comment by abenori** [comment]
ううむ，自力でコードを作ると駄目ですね．fe02876 でほぼ\@startsectionからのコピペにしました．（この修正を合わせて2018/06/17にしよう……．）

**Comment by kmaed** [comment]
ありがとうございます．今度こそ大丈夫だろうか．

**Comment by abenori** [comment]
また何かあったらお願いします．（\everypar怖い……）
