### ISSUE TITLE
句読点と縦中横の間に隙間が空く

### ISSUE THREAD

**Issue by hakuoku** [abenori/jlreq#32]
縦書きの際、通常の字の後では問題ないのですが、句読点の後で縦中横を使うと二分アキほどのスペースが空いてしまっているように見受けられます。

```tex
\documentclass[tate]{jlreq}
\begin{document}
誰かが\tatechuyoko{10}分前にここを

誰かが、\tatechuyoko{10}分前にここを
\end{document}
```

![2018-08-19_05h31_46](https://user-images.githubusercontent.com/24585873/44303051-8f8fd480-a371-11e8-92d5-a3ce972c4a1c.png)

**Comment by aminophen** [comment]
もしかして：\lastnodechar は JFM グルーノードを無視して最後の文字コードを返すはずなので，「\lastnodechar が -1 でない」かつ「最後のノードがグルーである」ならばそれは JFM グルーになるでしょうか？ もしそうだとすると

````
  \jlreq@lastnodechar=\lastnodechar
  \ifvmode\leavevmode\fi
  % 前のJFM glue
  \ifnum\jlreq@lastnodechar=-1\else
    \unskip

````

で良いことになります。

**Comment by abenori** [comment]
9ab8f80 で直しました．（合印部分と同じにしたのと\relaxに邪魔されていたのを回避しました．）
