### ISSUE TITLE
Tate mode for using Chinese font punctuation compress

### ISSUE THREAD

**Issue by asnahu** [abenori/jlreq#33]
When changing main font to chinese font, there no punctuation compress, how to solve  this problem? thanks!

**Comment by abenori** [comment]
Could you give me an example of the problem?

**Comment by asnahu** [comment]
Thanks  for reply. There are two screenshot:

![image](https://user-images.githubusercontent.com/19888895/47105505-b8035480-d276-11e8-8319-ad142dd683da.png)

![image](https://user-images.githubusercontent.com/19888895/47105684-32cc6f80-d277-11e8-955f-47071f14e562.png)

There is code for test:

`\setmainjfont{FZPingXianLanTingSong}`

**FZLanTingSong** is chinese font.

**Comment by abenori** [comment]
I used FZLanTingSong.ttf but I couldn't produce the problem. The code I tried is:

```latex
\documentclass[lualatex,tate]{jlreq}
\usepackage{luatexja-fontspec}
\setmainjfont{FZLanTingSong.ttf}
\begin{document}
あ，い。
\end{document}
```

Probably the same problem happens with `ltjtarticle' class. I guess that some font feature (vert) is not enabled.  But usually it is enabled by luatex-ja. Maybe you have to update luatex-ja?

**Comment by asnahu** [comment]
Is there any guide document for modify JFM? I've been read  luatexja document, but still not understand the structure of JFM, the real file is really complicated.

**Comment by abenori** [comment]
As far as I know, the only existing detailed document about JFM is the document of LuaTeX-ja package.

In the above example, I did the following. First copy `jfm-jlreq.lua` to some directory. (The JFM used in the example is `jfm-jlreqv.lua`, but this will be generated from `jfm-jlreq.lua`.) The JFM is defined as the table `jfm`. In `jfm-jlreq.lua`, you can find the code like :
 
````
jfm = {
  [1] = {
  ...
  }
 ...
}
````

Each entry indexed by the natural number gives the JFM for each character class. For example, the table in  `[1]` is the information of characters of class 1, namely opening brackets.

Now we want to add `left = -0.25` to class 1. The table is

```
  [1] = {
    chars = {<characters>},
    width = 0.5,height = 0.88,depth = 0.12,
    align = 'right',
    glue = {<glue table>}
  }
```

and there is no `left` property. So you can just add this entry to this table.

```
  [1] = {
    chars = {<characters>},
    width = 0.5,height = 0.88,depth = 0.12,
    align = 'right',
    left = -0.25, -- added
    glue = {<glue table>}
  }
```

To produce `jfm-jlreqv.lua` from this modified JFM, we use `make_variant_jfm.lua` script. Run this script in the directory where modified `jfm-jlreq.lua` is. Then the script produces new `jfm-jlreqv.lua`. (The script also proces other jfms. We do not need them here.) With this new `jfm-jlreqv.lua`, you will get the above example. (In fact, you also have to add `left = 0.25` to class 2 characters. The way to do this is the same.)
