### ISSUE TITLE
matter系のエラー

### ISSUE THREAD

**Issue by kmuto** [abenori/jlreq#38]
abenori_dev先端の82ea4490322184f2eeee22ad746531b467820c94 で実験していますが、

```
\documentclass[book]{jlreq}
\begin{document}
\frontmatter
\mainmatter
\backmatter
\end{document}
```

というのを用意したとすると、

3つのmatterがある状態では
```
! Undefined control sequence.
\backmatter ...terfalse \jlreq@backmatter@counter 
                                                  \jlreq@backmatter@heading ...
l.5 \backmatter
```

- frontmatterのみ あるいは frontmatter+mainmatterの場合はOK
- backmatterのみ あるいは frontmatter+backmatterの場合は上記エラー

mainmatterのみ あるいは mainmatter+backmatterの場合は
```
! Undefined control sequence.
<argument> \undefinedpagestyle 
                               
l.4 \mainmatter
```

となります。とりあえずbackmatterが動かなくなっているのが一番の問題ですね。

**Comment by abenori** [comment]
ありゃ，typoですね．  0f2ebed で直しました．

**Comment by kmuto** [comment]
お、通りました！

**Comment by kmuto** [comment]
でもmainmatterしかないときにエラーはまずいのかな

**Comment by abenori** [comment]
すみません忘れていた（ 85a9e5b ）

**Comment by kmuto** [comment]
通りました！

**Comment by abenori** [comment]
ありがとうございます！
