### ISSUE TITLE
改丁処理時のページスタイル

### ISSUE THREAD

**Issue by kmuto** [abenori/jlreq#39]
abenori_dev 1f0aac3132c1cbfa58e436224cf45daaecf95501 + LuaLaTeX/upLaTeX

たとえば奇数ページで終わったところに新たな章見出しがきたときには、改丁処理として中身が空の偶数ページが1つ差し込まれますが、その偶数ページのスタイルが「空スタイル（empty）」ではなく前の章のページスタイルになってしまうようです。

```
\documentclass[book]{jlreq}
\pagestyle{headings}
\begin{document}
\chapter{CH1}
\chapter{CH2}
\end{document}
```

上記の場合、CH2の前は空ページですが、CH1の柱・ノンブルが入っています。
JLREQ 4.1.4 改丁・改ページ・改段処理によれば、白ページにするのが妥当となっています。

実際の制作ではemptyよりも別のページスタイルを入れたい（たとえばmemoページスタイル）ということがあったりはするので、実装が面倒でなければ改丁の空ページに対して、emptyだけでなく任意のページスタイルも指定できると嬉しいです。

**Comment by abenori** [comment]
> 実際の制作ではemptyよりも別のページスタイルを入れたい（たとえばmemoページスタイル）ということがあったりはするので、実装が面倒でなければ改丁の空ページに対して、emptyだけでなく任意のページスタイルも指定できると嬉しいです。

JLReq的には白ページ固定なんで厳しいかも……．とりあえず`\pagestyle{empty}`固定で直しました． ff472e3 です．

**Comment by kmuto** [comment]
ありがとうございます。あえて変えたいときでもこれならさわるべき場所が明確なので大丈夫そうです。
