### ISSUE TITLE
caption_label_formatも図と表で分けたい

### ISSUE THREAD

**Issue by kmuto** [abenori/jlreq#41]
一般にキャプション位置が表は上、図は下のようにしますが、そのときに飾り（▼/▲）を付けたいことがあります。
figurename,tablenameを変えるという無理矢理な手法はありそうですが、formatで個々に変えられると助かります。

**Comment by abenori** [comment]
captionなんとかはさらに`figure=...`みたいなのを受け付けられるようにした方がよさそうですね．

**Comment by kmuto** [comment]
はい、ありがとうございます！

**Comment by abenori** [comment]
196ef40 で拡張してみました．

**Comment by kmuto** [comment]
`\jlreqsetup{caption_label_format={figure={▲#1},table={▼#1}}}` 動きました、ありがとうございます！

**Comment by abenori** [comment]
ちなみに`caption_font`とかも全部拡張しています．
