### ISSUE TITLE
柱とノンブルのフォントの区別

### ISSUE THREAD

**Issue by kmuto** [abenori/jlreq#42]
pagestyleの設定で、現状では柱・ノンブルともに必ず同一フォントに設定するようになっていますが、個別設定もできたほうがよさそうに思います（nombreパラメータに無理矢理フォント指定をつっこむことはできますが…）。

**Comment by kmuto** [comment]
ありがとうございます。偶数奇数ではさすがに変えません :)

**Comment by abenori** [comment]
48e7a6f で`nombre_font`と`running_head_font`を追加しました．（`nombre_ii_font`等もあります．）あ，`tate`が指定されたときのを全くチェックしてない……．

二つ目の柱（`running_head_ii`）などを指定した時の処理がおかしい気がするので，もう少し手を入れますが，通常利用では動くかと思います．

**Comment by kmuto** [comment]
確認しました、ありがとうございます！
