### ISSUE TITLE
enumerateのインデント

### ISSUE THREAD

**Issue by kmuto** [abenori/jlreq#43]
横書きenumerateの折り返し位置が左にはみ出る表現は意図的でしょうか。
JLREQ 図3.99は判断基準にならないですね…。

```
\documentclass{jlreq}
\begin{document}
\noindent
↓デフォルト

\begin{enumerate}
\item ああああああああああああああああああああああああああああああああああああああああああああああああああ
\end{enumerate}

\noindent
↓設定はともかくとして、こっちのほうの見た目が期待値？

\setlength\leftmargini{3\zw}
\begin{enumerate}
\setlength{\labelsep}{1\zw}\setlength{\itemindent}{0\zw}
\item ああああああああああああああああああああああああああああああああああああああああああああああああああ
\end{enumerate}
\end{document}
```

**Comment by abenori** [comment]
意図したような気はするのですが……何を参考にしたのか全く思い出せません．JLReqに箇条書きの記述は殆どないので，JISX4051かと思ったのですが，見当たりませんね……

**Comment by kmuto** [comment]
JISX4051の8.4 b-4)b-5)かなぁ。
> 4)順序ラベル及び項目ラベルは，行頭から字詰め方向に箇条内容の文字サイズで 2 倍分の領域に配置し，その領域内では，縦書きの場合は下側にそろえ，横書きの場合は右側にそろえることを既定値とする。
> 5)順序ラベルと箇条内容との字間の既定値は，箇条内容の文字サイズの全角アキとする。

「右揃え」ということから、
```
１２３４５６７８９
　・あああああああああ
　　ああああああああ

　1.あああああああああ
　　ああああああ

  10.いいいいいいい
　　いいいいい
```
というようにせよ、ということではないでしょうか。

**Comment by kmuto** [comment]
あ、ブラウザ表示によっては上の例ずれてるかも。「1.」と「10.」は左から2文字の範囲に右寄せで置き、箇条内容はラベル番号によらず3文字目位置で折り返し、ということです。

**Comment by abenori** [comment]
5)があるので，「1.」と「あ」の間は一文字分空けることになるかと思います．いずれにせよその辺が怪しいんですが，二行目以降どうなるか読める記述はないような気がします．謎です．

ただ，JLReqの図3.99はJISX4051 8.4 b-5)とは矛盾しているように見えるので，そもそもJISX4051に従うのもあまりよくないかもしれません．設定を新設しますかね……

**Comment by abenori** [comment]
やっぱり改行後に行頭がどこに配置されるかはJLReqにもJISX4051にも記述がないように思うので，パラメータでいじれるようにしました．次の設定を`\jlreqsetup`に新設しています（ 22f1947 ）．

* `itemization_labelsep`：ラベルと箇条内容との空き．
* `itemization_label_length`：ラベルの長さ．ただし（一回り上の環境の）行頭から数える．`i=2\zw,ii=3\zw`みたいな設定も可能．一行目の箇条内容のインデントがlabel_length + labelsepになる．

ちなみに二行目以降のインデントはLaTeXの流儀に従い`\leftmargin<i-vi>`で設定します．デフォルトをlabel_sep=0ptとし，label_lengthは`\leftmargin<i-vi>`と一致させたので，結果的にjsarticleなどに近い形になっていると思います．

JISX4051の8.4 b)の「既定値とする」という部分をパラメータ化しました．（labelsepが5)と6)，label_lengthが4)に対応．）ただJLReqの図3.99の説明を見ると，ラベル＋箇条内容を一つに見て，「一行目のインデント」「二行目以降のインデント」をパラメータと見ているように見えます．なので，JLReqに従うという方からするとあまりよくないかもしれません．

でもJISX4051も参照されているし……あーもう！

ご意見いただけるとありがたいです．よろしくお願いします．

**Comment by kmaed** [comment]
この件に関連するかわかりませんが，既定値での使用の際，文字サイズを変更したときに二行目以降のインデントが一行目とずれるのは意図通りなのでしょうか．

```latex
\documentclass{jlreq}
\begin{document}
\footnotesize
\begin{enumerate}
  %% \showthe\itemindent % -> -3.99994pt.
\item ああああああああああああああああああああああああああああああああああああああああああああああああああああああああああ
\end{enumerate}
\end{document}
```

**Comment by abenori** [comment]
ありがとうございます．意図したわけではないです．`itemization_label_length`の値が`2\zw`のようになっていて，文字サイズの変更に応じて小さくなってしまっていました．`\leftmargini`そのものにしました．
b4063ca

**Comment by kmaed** [comment]
ちゃんと揃うようになりました．ありがとうございました．
