### ISSUE TITLE
uplatex+bxemojiで表示されないものがある

### ISSUE THREAD

**Issue by kmuto** [abenori/jlreq#44]
すでにTwitterのほうのスレッドを拝見いただいているかもしれませんが、
https://twitter.com/zr_tex8r/status/1079270028082479105

abenori_dev先端 + BXcoloremoji-0.6＋upLaTeX にて、
```
\documentclass[a4paper,dvipdfmx]{jlreq}
\usepackage[utf8]{inputenc}
\usepackage[dvipdfmx]{graphicx}
\usepackage{amsmath}
\usepackage[twemoji-pdf]{bxcoloremoji}
\begin{document}
猫 \coloremoji{🐱} 寿司\coloremoji{🍣}
\end{document}
```

のようなサンプルで文字が表示されません。猫はx1f431、寿司はx1f363です。
プリアンプルを調整してLuaTeXで動かすと問題ありません。

これらのコード範囲は「範囲4」の設定だと思いますが、kcatcode 15になっているとこうなってしまい、18にしてみると確かに表示されました。

ucsコード番号指定の\coloremojiucsを使えば済むので今はさほど困ってはいないのですが、エラーも警告もなく静かに何も出てこないのも不気味な感じがあるので、何かcls側で対処できるということであればお願いしたいです。（LuaLaTeX 使えという話もある…）

**Comment by abenori** [comment]
https://twitter.com/zr_tex8r/status/1079268626710941697
みるとbxcoloremojiで対処できたりしないのかな？と思っているのですがどうなんだろう……．
そっちで対処できるならばその方が望ましいと思います．

**Comment by kmuto** [comment]
はい、こちらとしても現状で回避策はあるので、wont fixでも問題ないです。

**Comment by abenori** [comment]
https://twitter.com/zr_tex8r/status/1079538816745000960
https://twitter.com/zr_tex8r/status/1079601448407584768
とのことなので，そちらで対処してもらうことにします．（kcatcodeのデフォルトはどうするのがよいかは別に悩ましいですが……．）
