### ISSUE TITLE
jlreq-trimmarks.sty: pdfpagesと組み合わせたときの位置ずれ

### ISSUE THREAD

**Issue by kmuto** [abenori/jlreq#45]
pdfpagesのincludepdfの全面貼り付けがトンボでの変化に追従できておらず、おかしな位置にPDFが配置されるという問題があります。

gentombowで同じ問題があって、それについては以下のようなロジックで解決したようです。
https://github.com/aminophen/platex-tools/issues/4#issuecomment-353007052

実際、同じコードを使ってみたところ、jlreq-trimmarksの場合でも問題が解消されました。

**Comment by aminophen** [comment]
それは jlreq とは関係ないので，「plautopatch しましょう」な案件ではないかと…。或いは pxpdfpages パッケージでも良いです。

**Comment by kmuto** [comment]
ありがとうございます、ではこれはcloseしときます（ただjlreq-trimmarksはjlreqとは関係ない位置付けだったような？）。

**Comment by aminophen** [comment]
すみません，「jlreq とも jlreq-trimmarks とも関係なく，LuaTeX-ja や pLaTeX 自体のトンボ機能と pdfpages の互換性の問題だ」というつもりで書いていました。
