### ISSUE TITLE
twocolumn+目次+chapterの段抜き時の挙動

### ISSUE THREAD

**Issue by kmuto** [abenori/jlreq#46]
`\tableofcontents`を再定義すればよい話ではあるのですが、

以下のような2段組において、

```
\documentclass[book,twocolumn,twoside,line_length=20zw,number_of_lines=36]{jlreq}

\ModifyHeading{chapter}{
  column_spanning=true,% 段抜き
}

\begin{document}

\tableofcontents

\chapter{章ああああああああ}

あああああああああああああああああああああああああああああああああああああああああああああああああああああああああ
\end{document}
```

章見出しを段抜きするためにcolumn_spanningを有効にすると、目次の見出しもchapterで作られているために影響し、副作用として本来ちゃんとonecolumn化処理されている目次がtwocolumnになってしまうようです。

（line_length値は列の幅であり、2列紙面なら1列ぶんの幅を指定する、という理解でよいのですよね。）

**Comment by abenori** [comment]
うお，これはよくない．どーにかします．

> （line_length値は列の幅であり、2列紙面なら1列ぶんの幅を指定する、という理解でよいのですよね。）

はい，正しいです．

**Comment by abenori** [comment]
8de3650 で修正しました．

**Comment by kmuto** [comment]
ありがとうございます、修正されていることを確認しました。
