### ISSUE TITLE
How to setup tochu (頭注) by jlreq.cls in the environment of vertical layout (縱書) ? 

### ISSUE THREAD

**Issue by Steve-Cheung-emct** [abenori/jlreq#48]
I am a Chinese user of up-latex, this matter confuse me a long time.
By using `utbook.cls' with a style named tochu.sty written by  Shinsaku Fujita (藤田眞作),
it seemly worded out tochu, but soon or later, there would erupt a conflict punctuation, with ` ) ' landing on the first letter in a line.
So, how to setup tochu (頭注) by jlreq.cls in the environment of vertical layout (縱書) ?

**Comment by Steve-Cheung-emct** [comment]
Please help me and could you give out a sample.tex ?

**Comment by abenori** [comment]
Could you give me an example of a source code which produces the problem?

**Comment by Steve-Cheung-emct** [comment]
There were no problem, I just want to built touchu by using jlreq.cls. 

Thank you for your responding,
Good day!

**Comment by abenori** [comment]
Sorry, I miunderstood. I never used tochu.sty, but it seems that the following source code works.

````latex
\documentclass[tate]{jlreq}
\usepackage{tochu,plext}
\textwidth=39zw
\handurawidth=49zw
\marginparsep=2zw
\settochuu
\begin{document}
歌枕として、
\kyakuchutext{A1}{福島県白河市にあった奥州街道の関所。}
\kyakuchutext{A2}{%
芭蕉「おくのほそ道」
萩原 恭男 校注、岩波文庫七九 (一九九一)。}
\kyakuchutext{A3}{%
蓑笠庵 梨一「奥細道菅菰抄」(おくのほそみちすがもしょう。
文献\ref{A2}に付録として掲載)の注釈が、
典拠を明らかにしている。}
\kyakuchumark{A1}白河の関は古来有名である。
\end{document}
````

**Comment by abenori** [comment]
By the way, jlreq.cls provides `\sidenote` which produces footnote （脚注） in tate mode. WIth `\reversemarginpar`, this produces 頭注. It can be used like `\footnote`. It might help you. Here is an example.

````latex
\documentclass[
  tate,
  sidenote_length=10zw % length of 頭注
]{jlreq}
\reversemarginpar
\begin{document}
% Usual usage
この単語\sidenote{何か単語}を考える。

歌枕として、
\sidenotetext[2]{福島県白河市にあった奥州街道の関所。}
\sidenotetext[3]{%
芭蕉「おくのほそ道」
萩原 恭男 校注、岩波文庫七九 (一九九一)。}
\sidenotetext[4]{%
蓑笠庵 梨一「奥細道菅菰抄」(おくのほそみちすがもしょう。
文献2に付録として掲載)の注釈が、% one can't use \ref
典拠を明らかにしている。}
\sidenotemark 白河の関は古来有名である。
\end{document}
````

**Comment by Steve-Cheung-emct** [comment]
Thank you for your response. 
I choose to make touchu by touchu.sty  with sz.cls. (drawled by 小川 弘和(Shigaku Zasshi)，from http://www2.kumagaku.ac.jp/teacher/herogw/ )

His sz.cls can draw a vertical page heading on a side of page, I brought in a contents and many feathers, and I am willing to share with you. It contents about 1,100 lines. There is a shortcoming: if your just use \mcfamily to initialize the global font setting, it just collapsed and doomed. So I used a self-defined font-setting.

And my inspire is to imitate a closely style of old books, such like sangoku by handwriting or printed by wood block. 

In this ZIP file, there is a SZsample,  with SZ.cls.

[test.zip](https://github.com/abenori/jlreq/files/2756623/test.zip)

**Comment by abenori** [comment]
Thank you. Unfortunately my dvipdfmx prouces an error with your sample. `Failed to read UCS2/UCS4 TrueType cmap`

Only an information which may interest you. A heading which has a similar style as sz.cls can be also produced by jlreq. Here is an example. Note that `tate` mode in pagestyle is independent from `tate` mode of the article.

````latex
\documentclass[uplatex,tate,book]{jlreq}
\RenewPageStyle{plain}{
  tate,% tate mode pagestyle, 
  odd_running_head = {脂硯齋重評石頭記（清\quad 曹雪芹）},
  even_running_head = {脂硯齋重評石頭記（清\quad 曹雪芹）},
  nombre = {\kansuji\value{page}}
}
\pagestyle{plain}
\begin{document}
\chapter*{はじめに}
「東寺百合文書」に恵まれた播磨国矢野荘は、鎌倉後期以後の在地構造をめぐる諸問題について論じる際の主要な舞台とされている。そしてこれまでは、南北朝期における寺田法念排除による「悪党」問題解決の後に代官直務支配が成立し、それと百姓結合との対立関係が在地構造を規定する主要因になっていくと捉えられてきた\endnote{かかる理解は伊藤俊一「中世後期における『荘家』と地域権力」（『日本史研究』三六八、一九九三年）において総合?整理されている。}。しかし旧稿\endnote{拙稿「南北朝期矢野荘田所職考田所寺田浄信?田所代秀恵を中心に」（『日本史研究』四四九、二〇〇〇年）。}で指摘した如く、かかる理解には再考を要する。

そこで本稿ではまず「海老名文書」の現況に関する基礎的検討より浮かび上がる、室町期に到るまでの所職継承状況を俯瞰した後にそれを踏まえつつ、紙幅の制約から今回は鎌倉後期における「悪党」活動直前までに時期を限定して、その動向と位置について明らかにしていきたい。

\end{document}
````

**Comment by Steve-Cheung-emct** [comment]
Your example is excellent, thank you very much.

**Comment by neozhang1000** [comment]
> By the way, jlreq.cls provides `\sidenote` which produces footnote （脚注） in tate mode. WIth `\reversemarginpar`, this produces 頭注. It can be used like `\footnote`. It might help you. Here is an example.
> 
> ```
> \documentclass[
>   tate,
>   sidenote_length=10zw % length of 頭注
> ]{jlreq}
> \reversemarginpar
> \begin{document}
> % Usual usage
> この単語\sidenote{何か単語}を考える。
> 
> 歌枕として、
> \sidenotetext[2]{福島県白河市にあった奥州街道の関所。}
> \sidenotetext[3]{%
> 芭蕉「おくのほそ道」
> 萩原 恭男 校注、岩波文庫七九 (一九九一)。}
> \sidenotetext[4]{%
> 蓑笠庵 梨一「奥細道菅菰抄」(おくのほそみちすがもしょう。
> 文献2に付録として掲載)の注釈が、% one can't use \ref
> 典拠を明らかにしている。}
> \sidenotemark 白河の関は古来有名である。
> \end{document}
> ```

This works very well!
By the way, is there any way to have both footnote（脚注） and headnote（頭注）?
Thanks a lot!
