### ISSUE TITLE
BMP 外の文字

### ISSUE THREAD

**Issue by aminophen** [abenori/jlreq#49]
jlreq クラスの JFM/VF を使うと，BMP 外の文字が出ません。

現在の uptex-fonts は upjis 系がデフォルトですが，2018 年以降は Adobe-Japan1 の文字（具体的には[この一覧](https://github.com/texjporg/uptex-fonts/blob/master/source/makejvf-upjis.cnf)）に限り BMP 外でも使えるようにしてあるので，合わせていただければ幸いです。

```` tex
\documentclass[uplatex]{jlreq}
\begin{document}
𠮷野家
\end{document}
````

**Comment by abenori** [comment]
修正しました．（  26b50bb ）

**Comment by aminophen** [comment]
遅ればせながらリリース版に反映されていることを確認しました。ありがとうございます。
