### ISSUE TITLE
bibitem labels in tate (縦書) mode

### ISSUE THREAD

**Issue by otyu** [abenori/jlreq#50]
When using labels for bibliographic items, those are not displayed in vertical mode.

MWE:
```
\documentclass[uplatex,report,a4paper,landscape,tate]{jlreq}
\begin{document}

一心・・・「②心を統一すること。精神統一・禅定に同じ。心の動揺を静めること。心静かなこと。一心に阿弥陀仏をたのむというように、弥陀一仏を念じて、他の仏を念じないの無二の一心といい、念仏一行を相続して余行をまじえないことを専一の一心という。純なる信心。邪念をまじえず、二心のないこと。」\cite{butsu}

これ\cite{gorin}もこれ\cite{as}も参考した。

\begin{thebibliography}{99}
\bibitem[仏辞]{butsu} 中村元（著）　『広説佛教語大辞典縮刷版』　東京書籍　２０１０年
\bibitem[漢林]{gorin} 『新漢語林』第二版　大修館書店
\bibitem[AS64]{as} M.~{Abramowitz} and I.~A. {Stegun},
 \textsl{ Handbook of Mathematical Functions with Formulas, Graphs,
  and Mathematical Tables},
  Applied mathematics series, United States Department of Commerce,
  National Bureau of Standards, 1964.
\end{thebibliography}
\end{document}
```

The result (cropped) is the following.

![forgit](https://user-images.githubusercontent.com/12646940/57595702-333f9700-7536-11e9-83a9-58b381170656.png)

Maybe it would be better if the labels (and brackets) could be displayed vertically.

(Thank you very much for your time.)

**Comment by abenori** [comment]
Thank you. I agree with you. I'll fix it later.

**Comment by abenori** [comment]
Sorry for my late work. I remember that I changed the labels as in the example at some point, but I forgot why I did it. I reverted it to the original LaTeX style ( e3ad7c9 ). It might cause another problem. Please let me know if something happens, or you find a better way.

**Comment by otyu** [comment]
Dear maintainer, I am very sorry for my late answer.

Thank you for your work. I have been using the project since the commit and it has been working wonders!

Also, I did not know I could close the issue, so I will do so now.

(Again, thank you very much for your time.)
