### ISSUE TITLE
割注使用時の強制改行

### ISSUE THREAD

**Issue by isamuwada** [abenori/jlreq#52]
jlreq の warichu を利用すると割注の直前に強制改行が入ってしまいます。
該当箇所のコメントをみると【「初回」時はここに強制改行を入れる】の記述があるので .aux から取り込むのかとおもい二回通したり、二箇所記述したりしましたがいずれも強制改行されてしまいます。

トレースしてゆくと \jlreq@rest@linewidth で　\jlreq@reference@label　　でjlreq@rest@width.pos.X.\the\jlreq@reference@count　を設定しようとしているようですが、その直後  \jlreq@reference@ifexist にてその設定情報をチェックしていますが 偽となり 　\@firstoftwo にあたえられる {\\}{} の{\\} が採択され強制改行になっているのだと思います。

サンプルソースは以下のとおりです。使用方法に間違いがあれば指摘していただければ幸いです。

\documentclass[%
      uplatex,
%%    tate,
]{jlreq}

\begin{document}

割注を利用すると強制改行\warichu{何故改行されるのかな}されてしまう。

jlreq.cls に記述されたつぶやき\warichu{「初回」時はここに強制改行を入
  れる．これにより現在位置の取得がより正しくなる……といいなぁ}が気になる。

\end{document}

**Comment by abenori** [comment]
お察しの通り初回のみ強制改行のつもりだったのですが，条件分岐の部分が二重にバグっていました．直しました． 8c7a31a

**Comment by zr-tex8r** [comment]
修正箇所の3行上にある`\jlreq@reference@ref`も「よく似たコード」なんですけど、こちらはあってるのでしょうか？

**Comment by abenori** [comment]
まずいですー b9ea7b5
