### ISSUE TITLE
縦書き時の追出し量について

### ISSUE THREAD

**Issue by ofk** [abenori/jlreq#57]
バグ報告というよりは質問寄りです。

縦書き・ぶら下げ有効でutbookと比較して疑問に思う挙動がありました。以下はインデントなし・10文字折返しで比較したものです。

utbook:

<img width="449" alt="スクリーンショット 2019-09-08 11 12 06" src="https://user-images.githubusercontent.com/280562/64482270-bdb8ae80-d229-11e9-8325-0b5d42519498.png">

jlreq:

<img width="447" alt="スクリーンショット 2019-09-08 11 12 18" src="https://user-images.githubusercontent.com/280562/64482273-d032e800-d229-11e9-921a-c254f652309a.png">

（上記は[gist](https://gist.github.com/ofk/f90a33c241495ccc2703069d622476d0)にすべてのコード、Dockerfileを置いています）

jlreqは一文字の追出しをしないのですが、これは仕様でしょうか？（日本語組版処理の要件を調べているのですがわからず……）
また、もしutbookと同じような見栄えにしたい場合は、どのような変更を入れればいいでしょうか？（できればstyファイルの書き換えではなく何らかの設定で）

**Comment by ofk** [comment]
ブログの[jlreq.clsの(x)kanjiskipの話](http://abenori.blogspot.com/2018/12/jlreq.html)に示されているkanjiskipの上書きを試したところ解決しました。上書き可能なことに気づいていませんでした。

**Comment by abenori** [comment]
> jlreqは一文字の追出しをしないのですが、これは仕様でしょうか？（日本語組版処理の要件を調べているのですがわからず……）

「日本語組版処理の要件」では3.5.4に記述があります．pTeXでは`\jcharwidowpenalty`という値で設定することになります．（大きい方がより追い出しを許さないことになる．）よって，`\jcharwidowpenalty=0`により，「一文字の追出しを絶対に許す」という設定ができます．

が，今回はお気づきの通りkanjiskipのでかさのせいでしょう．デフォルトでは`\jcharwidowpenalty`の値は500です．これはあまり大きい値ではないので，utbookでは一字配置する方がよいと判断されたようです．お気づきの通り，jlreqはkanjiskipの値がかなり伸びやすいので，文字間の空きを増やしてでも一文字のみになることを避けた方が得策であると判断されたようです．
