### ISSUE TITLE
twocolumnにおいて複数行取り見出しが収まらないときに行送りが変化する

### ISSUE THREAD

**Issue by kmuto** [abenori/jlreq#58]
twocolumnで2列化しているときに、列末尾で複数行取り見出しが「ギリギリ入らない」と、
単にアキを入れるわけではなく、本文側の行送りを変えて収めようとするという挙動になります(masterおよびabenori\_dev HEADでテスト)。これは1段組のときには発生しません。

JLREQでこのあたりをどうするか、という明確な定義は見つけられなかったのですが、普通の制作だとこのやり方は見かけないように思います。

ひとまず手元では手動で\clearpageなどして強制的に送れば行送りの変化は防げています。

```
\documentclass[paper=a5,twocolumn]{jlreq}
\usepackage{jlreq-trimmarks}

\newcounter{L}
\newcommand{\mywhile}[1]{
  \setcounter{L}{0}%
  \loop%
  \ifnum\value{L}<#1%
  {\noindent ■■■■■■■■■■■■■■\par}
  \stepcounter{L}%
  \repeat%
}

\begin{document}

\mywhile{50}

\section{HI}

\end{document}
```
![two](https://user-images.githubusercontent.com/183523/72682466-a0b5b580-3b10-11ea-8cea-0a9e54d43908.png)

**Comment by abenori** [comment]
なるほど，把握しました．`\parskip`で伸びているみたいです．jarticleやjsarticleでは起こらないようですね．

* jsarticleでは`\parskip=0pt`．
* jarticleでは`\raggedbottom`になっている．

何も考えずに`\parskip`はjarticleからもってきて，jsarticleをまねて`\flushbottom`を実行したらこうなったようです．

**Comment by abenori** [comment]
ちなみに組版としては`\raggedbottom`よりも`\flushbottom`の方が望ましいのでしょうか？

**Comment by kmuto** [comment]
ありがとうございます、jlreq.clsの「最終処理」の箇所をraggedbottomにしたら確かに意図どおりにいきました。

> ちなみに組版としては\raggedbottomよりも\flushbottomの方が望ましいのでしょうか？

いやー、2段にするからには列左右で行が揃うのを期待するはずで、flushbottomは変だと思います。
1段でも、下埋めのために行間を変える、というのも普通やらないですね。

**Comment by munepi** [comment]
> なるほど，把握しました．`\parskip`で伸びているみたいです．jarticleやjsarticleでは起こらないようですね．
> 
> * jsarticleでは`\parskip=0pt`．
> * jarticleでは`\raggedbottom`になっている．
> 
> 何も考えずに`\parskip`はjarticleからもってきて，jsarticleをまねて`\flushbottom`を実行したらこうなったようです．

以下でよいと思います。某弊社は、標準でこうしています。

問題を分けて考えると、
 * まず、本issueの原因は、 `\parskip` の間延びに依ります。
 * その上で、段組みしたときに、（版面天・地を基準にした）左右の列を基本的に揃えるとなると、 `\flushbottom` を入れておくと思います。もしこの `\flushbottom` を `\raggedbottom` にしてしまうと、行取りにしていない図・表、別行立て数式のブロック要素が入ると、版面地で揃わなくなってしまいます。

```
\setlength\parskip\z@skip
\if@twocolumn
  \twocolumn
  \sloppy
  \flushbottom
\else
  \onecolumn
  \raggedbottom
\fi
```

**Comment by abenori** [comment]
ありがとうございます．結局jsclasses通りにすればよかったという……（よくあるはなし）

というわけで：0cd1bf9 Underfullでちゃうけど仕方ないですかね．

ちなみに一段組は`\raggedbottom`でいんですか？
