### ISSUE TITLE
twocolumn時のmarginparのparsep,width

### ISSUE THREAD

**Issue by kmuto** [abenori/jlreq#59]
```
\documentclass[twocolumn]{jlreq}
\begin{document}
ああああああああああああああああああああああああああああああああああああああああ
あ\marginpar{まーじんぱらぐらふ}
\end{document}
```
のようにしたときにmarginparsepが0、marginparwidthが1zw程度になります。ロジックを見ると仕様としてあえてこうされている(ユーザがmarginsep,marginparwidthを指定する)のでしょうか。

jlreq 1段のときはparsep 2zw、parwidth 2zwくらいになるようです。jsbook+twocolumnではparsep 2zw、parwidth 3zwになりました。

33a5389f86b27e30ca00774b786f31e8f0ae05d6 での実行です

**Comment by abenori** [comment]
こちらでは一段組でも二段組みでも`\marginparsep`，`\marginparwidth`ともに0ptです．

````
\documentclass[twocolumn]{jlreq}
\begin{document}
marginparwidth=\the\marginparwidth , marginparsep=\the\marginparsep

ああああああああああああああああああああああああああああああああああああああああ
あ\marginpar{まーじんぱらぐらふ}
\end{document}
````

クラスオプションの`sidenote_length`に正の値を入れてやれば`\marginparwidth`はその値になり，`\marginparsep=2zw`となります．デフォルトでは`sidenote_length=0pt`です．

**Comment by kmuto** [comment]
申しわけない、変に数値で出さずに形で示せばよかったです、

marginparに入れたものが1列だと版面より外に、2列だと版面内に重なる というのは意図的でしょうか。

![margin-1](https://user-images.githubusercontent.com/183523/73144325-1d83f900-40e8-11ea-8d5d-825843c8eeb4.png)
![margin-2](https://user-images.githubusercontent.com/183523/73144327-207ee980-40e8-11ea-9abd-c650bd32d2ae.png)

**Comment by abenori** [comment]
結果的には意図的ということになるかなと思います．もうちょっというと，`\marginpar`使うな，使いたければ`sidenote_length`設定しろ，ということでしょうか．

1. `\marginpar`を傍注専用として占有している．（`\sidenote`内で利用．）
2. `sidenote_length=0pt`の時は文書作成者は「傍注を使わない」と宣言しているものと見なしている．
3. 従って，`\marginpar`は使わないと文書作成者は宣言していると見なされている．

（あまり現実的な論理ではない気もしてきました．傍注を`\marginpar`抜きで実装できればよいのですが……．）

**Comment by kmuto** [comment]
意図的とのことで、ありがとうございます(逆に1段のほうがおかしいのか…)。

marginparは本来の使い方というより単に編集者コメントを入れるのに流用していただけだったりしますが、`sidenote_length`で対処するようにしますね。

**Comment by abenori** [comment]
> 単に編集者コメントを入れるのに流用

これ自分もやるのでやっぱり何か考えた方がよい気がしてきました．`sidenote_length`ですが，設定すると傍注部分も本文の一部と見なした版面になるので気をつけてください．（gutterを省略しても本文範囲が中央配置されなくなる，柱などが傍注部分の上に出るようになる，など．）
