### ISSUE TITLE
引用系環境にoption

### ISSUE THREAD

**Issue by earthoul** [abenori/jlreq#6]
現行の引用系の挙動は、

* 2字下げ
  * `quote`なら先頭行さらに1字下げ
  * `quotation`なら先頭行も含め段落ごとに1字下げ
* 2字上げ
* 前後0行アキ（アキなし）
* 本文と同じ文字サイズ

ですね。ただ、JLReq 3.5.2, 3.5.3, 4.5.2, 4.5.3に鑑みると、optionが欲しくなります（引用単位で変わるとも思われないので文書単位のoptionでしょう）。2字下げは揺るぎないものとして、

* `quote`の先頭行字下げ：`[0/1]`
* 字上げ：`[0/2]`
* 前後の行アキ：`[0/1]`
* 引用の文字サイズ：`[normal/footnotesize]`

辺りは選択可能になるとよいなぁ、と感じます。当方の好みはそれぞれ0, 0, 1, normalですが、既定値がどうなるのがいいのかは自信ありません……。

（ちなみに、“複数段落の引用（`quotation`相当）でも天付き”で組まれた出版物も若干数見かけましたが、このパターンはJLReqに記載がなかったので上記箇条書きでは触れませんでした）

**Comment by abenori** [comment]
（後でJLReqをもう一度きちんと眺めてみますが）確かにそのあたりは設定できるように見えますね．字下げも2文字とは限らないようなので，そちらも指定できると良さそうです．

文字サイズは，quote_font={\footnotesize}みたいな指定と，quote_size={footnotesize}みたいなのどっちがいいかなぁ．（前者だとフォントも変更できちゃうから後者かな？）

**Comment by abenori** [comment]
abenori_dev の 73972fb でやってみました．字下げ/字上げ/フォントサイズ/前後アキを指定できるようにしています．一行目の字下げの指定はしていませんが，quote=一切字下げ無し，quotation=字下げで良いかなと思っています．（というかLaTeX2eのよくあるクラスではこうなっているわけで，quoteで下がっていたのはミスですね．）
