### ISSUE TITLE
Japanese fonts and glyph

### ISSUE THREAD

**Issue by c933103** [abenori/jlreq#60]
In other similar documents like clreq and alreq, they have included some sections to talk about specific detail of fonts for those languages that designers or programmers might need to beware of when dealing with those languages, but I have not see similar content in jlreq. Should jlreq add a few sections to cover soecific details about Jaoanese fonts and glyphs, like common Japanese font families, Glyph of Japanese font for some Unicode code points versus other non-Japanese fonts, ideograph variation sequences, and other possibly relevant content?

**Comment by yuw** [comment]
Is this topic an issue for another project? (see https://github.com/w3c/jlreq)

**Comment by c933103** [comment]
Ah right, sorry for posting on incorrect project.
