### ISSUE TITLE
縦書き時に tikz や pdfpages のサポート

### ISSUE THREAD

**Issue by ktrxcmsn** [abenori/jlreq#65]
`tate` オプションや `\tate` 命令時に `tikz` や `pdfpages` のサポートを検討してただければと思います。
### 環境

- macOS 10.15.6
- LuaHBTeX, Version 1.12.0 (TeX Live 2020)
- 他も最新版です

### `tikz`
現状では縦書き時はエラーがでます。横書き時（\yoko）ではエラーは出ません。`ltjtarticle.cls` ではエラーは出ません。
```Latex
\documentclass[a4paper, lualatex, tate]{jlreq}
% \documentclass{ltjtarticle}  % ltjtarticleではエラーにならない
\usepackage{tikz}

\begin{document}
% \yoko  % 横組みにするとエラーにならない
% \tate  % オプションの代わりにコマンドでもエラーになる
\begin{tikzpicture}
  \draw (0,0) -- (1,0) -- (1,1) -- cycle;
\end{tikzpicture}
\end{document}
```

### `pdfpages`
縦書き時でも `hyperref` を読み込むとエラーがでません。横書き時は `hyperref` がなくてもエラーはでません。
```Latex
\documentclass[a4paper, lualatex, tate]{jlreq}
\usepackage[unicode=true]{hyperref}  % コメントアウトするとエラー
\usepackage{pdfpages}

\begin{document}
初頁
\clearpage
\includepdf{sample.pdf}
終頁
\end{document}
```

**Comment by abenori** [comment]
とりあえず両方ともエラーになることを確認しました．後ほど調べてみます．

**Comment by kmaed** [comment]
tikz の方は，ltjtarticle.cls にある次のコードを jlreq.cls の最初の方に入れておくと回避できるようです（私は何も理解していない）．
``` latex
\AtEndOfPackageFile{everyshi}{%
  \def\@EveryShipout@Output{%
    \setbox8\vbox{%
      \yoko
      \@EveryShipout@Hook
      \@EveryShipout@AtNextHook
      \global\setbox\luatexoutputbox=\box\luatexoutputbox
    }%
    \gdef\@EveryShipout@AtNextHook{}%
    \@EveryShipout@Org@Shipout\box\luatexoutputbox
  }}
```

pdfpages の方は ltjtarticle でも同じエラーが出るので，luatexja の問題ではないかと思います．[luatexja のチケット](https://osdn.net/projects/luatex-ja/ticket/40596)を作っておきました．

**Comment by kmaed** [comment]
`\tate` とパッケージの組み合わせでエラーが出るみたいなのは，個々の文書クラスで対応するよりは `luatexja` 本体側でなんとかするべきな気がしますね．

**Comment by abenori** [comment]
そんな気もしますね．上のコードをlltjp-everyshi.styに移してみました．しかしそうなっていなかったということは何かまずい点があるのかな．

**Comment by h-kitagawa** [comment]
> 上のコードをlltjp-everyshi.styに移してみました．しかしそうなっていなかったということは何かまずい点があるのかな．

どうもありがとうございます．たぶんそんな深い意味はなくて，ltjt{article,book,...} 以外の縦組クラスを気にしていなかっただけのような気がしています．

**Comment by abenori** [comment]
ありがとうございます．これでどちらの問題も次バージョンのLuaTeX-jaで解決されそうですね．

**Comment by abenori** [comment]
LuaTeX-jaの2020-08-02で解決済みです．

**Comment by ktrxcmsn** [comment]
確認しました。
対応をありがとうございました。

**Comment by ktrxcmsn** [comment]
縦書き `figure` 環境中で `\yoko` と `tikz` を併用するとエラーになりました。`ltjtarticle.cls` ではエラーはでません。
`luatexja` で報告すべきか判断できず、こちらに報告させていただきます。

```LaTeX
\documentclass[lualatex, paper=a7, tate]{jlreq}
\usepackage{tikz}
\begin{document}
% \yoko  % ここだとエラーにならない
\begin{figure}
  \yoko  % ここだとエラーになる
  \tikz\draw[ultra thick] (0,0) rectangle (1,1);
\end{figure}
\end{document}
```

#### Error message
```
! Output loop---100 consecutive dead cycles.
\clearpage ...rite \m@ne {}\vbox {}\penalty -\@Mi 
```

#### Version
lualatex: LuaHBTeX, Version 1.12.0 (TeX Live 2020)
jlreq.cls: 2020/12/29

**Comment by kmaed** [comment]
そもそも platex でも次で同じエラーが出るようです．
```latex
\documentclass{article}
\begin{document}
\tate
% \yoko  % ここだとエラーにならない
\begin{figure}
  \yoko  % ここだとエラーになる
  a
\end{figure}
\end{document}
```

**Comment by kmaed** [comment]
luatexja だとちょっと不思議．
```latex
\documentclass{article}
%% \documentclass{ltjarticle}   % こちらだとエラーにならない
\usepackage{luatexja}
\usepackage{tikz}               % 読まないとエラーにならない
\begin{document}
\tate
% \yoko  % ここだとエラーにならない
\begin{figure}
  \yoko  % ここだとエラーになる
  a
\end{figure}
\end{document}
```

**Comment by aminophen** [comment]
> そもそも platex でも次で同じエラーが出るようです．

エラーの発端は `\@testwrongwidth` が誤判定していることのようです。組方向が食い違っているせいか `\dp` の取得が正しくならず，double column float -- wrong になっている？

**Comment by abenori** [comment]
（見落としていました……）

とりあえず https://github.com/texjporg/platex/issues/95 に転送しました．
