### ISSUE TITLE
Broken link in README-ja.md

### ISSUE THREAD

**Issue by xfq** [abenori/jlreq#66]
W3C published a [new version](https://www.w3.org/TR/2020/NOTE-jlreq-20200811/) of jlreq yesterday and broke a link in README-ja.md. We (the W3C i18n WG) may set up a redirect in the future, but before that happens it would be helpful to change the link in [README-ja.md](https://github.com/abenori/jlreq/blob/master/README-ja.md#%E3%81%93%E3%82%8C%E3%81%AF%E4%BD%95) from https://www.w3.org/TR/jlreq/ja/ to https://www.w3.org/TR/jlreq/?lang=ja

Thank you for working on this!

**Comment by abenori** [comment]
Thank you.
