### ISSUE TITLE
縦組の enumerate と itemize の itemization_labelsep

### ISSUE THREAD

**Issue by aminophen** [abenori/jlreq#67]
#43 と関係があるような気もしましたが，主な違和感は縦組の時なので別 issue にします。

``` tex
\documentclass[tate]{jlreq}
\begin{document}

enumerate
\begin{enumerate}
\item 箇条書きで
\item 書いてみる。
\end{enumerate}

itemize
\begin{itemize}
\item 箇条書きで
\item 書いてみる。
\end{itemize}

\end{document}
```

これだと enumerate のラベル「一」「二」が箇条内容とくっつきます。

<img width="293" alt="20201009-jlreq-enumerate" src="https://user-images.githubusercontent.com/9957466/95594790-61f0d280-0a86-11eb-89a7-437598311b19.png">

`\jlreqsetup{itemization_labelsep=1zw}` を足すと，今度は itemize のラベルが離れます。

<img width="270" alt="20201009-jlreq-enumerate-1" src="https://user-images.githubusercontent.com/9957466/95594878-73d27580-0a86-11eb-99f6-37f3e7271322.png">

別々に設定できる方法はあるでしょうか。

**Comment by abenori** [comment]
実は`\jlreqsetup{itemization_labelsep={enumerate=1zw}}`とかけます．

**Comment by aminophen** [comment]
お返事遅くなりすみません。指定方法があったのですね。ありがとうございます。README に項目がなかったのもあり，気づきませんでした。
