### ISSUE TITLE
\sffamily 使用時に和文ファミリも追従させる

### ISSUE THREAD

**Issue by yudai-nkt** [abenori/jlreq#7]
現状では

```latex
\documentclass[uplatex]{jlreq} % platex, lualatex も同様
\begin{document}
\sffamily ゴシック体とsan serif
\end{document}
```

などとした場合に，「ゴシック体と」の部分が明朝体のままで出力されます。これが upLaTeX の既定であることは認識していますが，JS 文書クラスのように `\sffamily` で和文ファミリが連動して `\gtfamily` に切り替わってくれるとありがたいです。

JLREQ を精査せずに issue を立てて恐縮ですが，日本語版をざっと検索した限りでは「セリフ」という語が見当たらず，[4.1.9][processing of runin heading] の

> 先頭に付くアラビア数字又は欧文用文字（cl-27）の番号をゴシック体又はウェイトの太い書体にし，

という記述を踏まえてもゴシック体とサンセリフ体を区別していないように見受けられるので，両ファミリを連動させても JLREQ に違反する設計にはならないように思います。

[processing of runin heading]: https://www.w3.org/TR/jlreq/ja/#processing_of_runin_heading

**Comment by abenori** [comment]
すみません，どちらかというと忘れていました．abenori_devの f597344 で連動させるようにしました．

**Comment by yudai-nkt** [comment]
手元に clone して確認できました。対応ありがとうございます。
