### ISSUE TITLE
lualatex で overfullrule が倍増する

### ISSUE THREAD

**Issue by aminophen** [abenori/jlreq#70]
lualatex の時だけ \overfullrule が倍増することに気づきました。

``` tex
%#!lualatex
\documentclass[lualatex,a4paper,draft]{jlreq}
\begin{document}

ABC,abc,ABC,abc,ABC,abc,ABC,abc,ABC,abc,%
ABC,abc,ABC,abc,ABC,abc,ABC,abc,ABC,abc,ABC,abc,
ABC,abc,ABC,abc,ABC,abc,ABC,abc,ABC,abc,%
ABC,abc,ABC,abc,ABC,abc,ABC,abc,ABC,abc,ABC,abc,

\end{document}
```

### lualatex

<img width="294" alt="20201130-lualatex-overfull" src="https://user-images.githubusercontent.com/9957466/100615491-042c8880-335b-11eb-8058-b3144373e7b0.png">

### platex

<img width="288" alt="20201130-platex-overfull" src="https://user-images.githubusercontent.com/9957466/100615505-068ee280-335b-11eb-869b-6e535a3e2e5b.png">

通常，最終組版時には draft を外しますから些末な問題ですが，理由は何でしょうか。（今回気づいたのは，某ドキュメントに「overfull を引き起こすソースとその出力例」を示そうとした為です。）

**Comment by kmaed** [comment]
`luatexja-adjust.sty` を読むと2つ出ますね．

```latex
\documentclass[a4paper,draft]{ltjsarticle}
%\usepackage{luatexja-adjust}
\begin{document}

ABC,abc,ABC,abc,ABC,abc,ABC,abc,ABC,abc,%
ABC,abc,ABC,abc,ABC,abc,ABC,abc,ABC,abc,ABC,abc,
ABC,abc,ABC,abc,ABC,abc,ABC,abc,ABC,abc,%
ABC,abc,ABC,abc,ABC,abc,ABC,abc,ABC,abc,ABC,abc,
\end{document}
```

**Comment by kmaed** [comment]
`priority=false` だと出ないです．

```latex
\documentclass[a4paper,draft]{ltjsarticle}
\usepackage{luatexja-adjust}
\ltjenableadjust[priority=false]
\begin{document}

ABC,abc,ABC,abc,ABC,abc,ABC,abc,ABC,abc,%
ABC,abc,ABC,abc,ABC,abc,ABC,abc,ABC,abc,ABC,abc,
ABC,abc,ABC,abc,ABC,abc,ABC,abc,ABC,abc,%
ABC,abc,ABC,abc,ABC,abc,ABC,abc,ABC,abc,ABC,abc,
\end{document}
```

**Comment by abenori** [comment]
改行処理をし直すたびに入っちゃうという感じですかね．Overfull警告の数も倍増しているみたいです．とりあえずLuaTeX-jaの方に転送します．

**Comment by h-kitagawa** [comment]
対策を施した LuaTeX-ja 20201224.0 を出しました．

**Comment by aminophen** [comment]
ご対応ありがとうございます。
