### ISSUE TITLE
pagestyle で position=top-* を設定するとタイトルページでスタイルが適応されない

### ISSUE THREAD

**Issue by ktrxcmsn** [abenori/jlreq#72]
`pagestyle` で `running_head_position=top-left` や `top-right` 設定した場合、タイトルページでスタイルが適応されなくなります（以降のページではスタイルが適応されています）。
 
```LaTeX
\documentclass[lualatex, paper=a7]{jlreq}
\NewPageStyle{myplain}{
    yoko,
    % スタイル適応の確認のため
    nombre_position=bottom-right,
    odd_running_head={はしら},
    % bottom にすると
    % タイトルページにもpagestypeが適用される
    running_head_position=top-left,
    % running_head_position=bottom-left,
}
\pagestyle{myplain}
\begin{document}
\title{あ}
\maketitle
い
\newpage
う
\end{document}
```
#### Version
lualatex: LuaHBTeX, Version 1.12.0 (TeX Live 2020)
jlreq.cls: 2020/12/29

**Comment by abenori** [comment]
よくあるクラスファイルと同様，`\maketitle`のあるページではページスタイルがplainに戻ります．ただし，（jsclassesに合わせて）`\pagestyle{empty}`の時だけは維持するようにしています．というのがしたかった部分なのですが，なぜか「ヘッダが空の時に維持する」になっていました．

というわけでabenori_dev 3614ae0 で直しました．topでもbottomでも「はしら」は出力されないようになったはずです．

**Comment by ktrxcmsn** [comment]
「はしら」が出力されなくなっていることを確認しました。
`jsclasses` と同様 `\thispagestyle` でタイトルページのページスタイルの変更もできました。
ご対応をありがとうございます。
