### ISSUE TITLE
hyperref を読み込むと縦書き時の目次のページが横書きになる

### ISSUE THREAD

**Issue by ktrxcmsn** [abenori/jlreq#75]
`hyperref` を読み込み縦書きで目次を生成すると、目次に出力されるページが横書きになります。読み込んでいなければ、縦書きで出力されます。

```LaTeX
\documentclass[lualatex, tate, paper=a7]{jlreq}
\usepackage[unicode=true]{hyperref}  % 読み込んでいなければページは縦書き
\begin{document}
\tableofcontents
\section{あ}
\subsection{い}
\section{え}
\end{document}
```
<img width="300" alt="イメージ" src="https://user-images.githubusercontent.com/68729196/103520582-b5729100-4eba-11eb-9e4e-7f2d687c9d11.png">

#### Version
LuaLaTex: Version 1.12.0 (TeX Live 2020)
jlreq.cls: 2020/12/29

**Comment by abenori** [comment]
jlreqが設定している`\addcontentsline`をhyperrefが定義しなおしてしまっているからなので，hyperrefにあうように再度定義し直せばよいです．が，これをjlreqに仕込んでしまうとhypperrefの更新に追随していかないとならなくなり，あまり実行できる自身がありませんので，そのままにさせてください．なお，同様の症状はltjtarticleでも起こります．

とりあえず

```latex
\patchcmd{\addcontentsline}{\thepage}{\tatechuyoko{\thepage}}{}{}
```

をソースに書いておく，でどうでしょう？

**Comment by ktrxcmsn** [comment]
`\patchcmd` で、目次でも `\tatechuyoko` が効くように解決できました（`patchcmd` パッケージを知りませんでした…）。
`hypperref` に追従するのは大変かと思いますので、私も現状で問題ないと思います。
ご対応ありがとうございました。
