### ISSUE TITLE
uplatex で Package inputenc Error: Unicode character ︎ (U+FE0E)

### ISSUE THREAD

**Issue by tkurita** [abenori/jlreq#77]
すいません。最新のものにアップデートすると以下のエラーは発生しなくなりました。
この issue を削除したいのですが、自分ではどうもできず。ゴミを残してしまったようで、すいません。

ソースに「×」が含まれていると、
Package inputenc Error: Unicode character × (U+00D7)
というエラーが発生します。
ujarticle では発生しません。

**Comment by abenori** [comment]
閉じてしまえば良いかと思います．
