### ISSUE TITLE
\paragraph, \subparagraph の引数内でコマンドを使うとエラーが発生する

### ISSUE THREAD

**Issue by tkurita** [abenori/jlreq#78]
\paragraph{あああ\textit{A}あ}

のように paragraph もしくは subparagraph 内でコマンドを使うと、以下のエラーが発生します。

! Argument of \jlreq@RuninHeading@start@ has an extra }.
<inserted text> 
                \par 

ujarticle では発生しません。

**Comment by abenori** [comment]
ありがとうございます．直しました． 3742d07

**Comment by tkurita** [comment]
ありがとうございます。修正されていることを確認しました。
