### ISSUE TITLE
PDF in Tate mode, text order is incorrect

### ISSUE THREAD

**Issue by asnahu** [abenori/jlreq#82]
<img width="240" alt="image" src="https://user-images.githubusercontent.com/19888895/112445265-849b4d00-8d81-11eb-9199-e40fbad44194.png">

text ordering is not like in yoko mode. how to solve this problem? thanks!

**Comment by abenori** [comment]
It seems fine with my computer. Could you tell me the issue more?
<img width="176" alt="jlreq" src="https://user-images.githubusercontent.com/522782/112447221-68ed7200-8d94-11eb-9bdd-7287521eb622.png">

**Comment by asnahu** [comment]
`% !TEX ts-program = LuaLatex
% !TEX encoding = UTF-8

\documentclass[
	lualatex,
	a6paper,
	book,
    12pt,
]{jlreq}
\usepackage{luatexja-fontspec}
\usepackage{luaotfload}
\usepackage[right=.3in, left=.3in, top=.3in, bottom=.3in]{geometry}
\parindent=2em
\setmainjfont      { KozMinPr6N-Medium } 

\begin{document}

丁元英回答道:「大師考問晚輩自在情理之中，晚輩就斗胆妄言了。所謂真經，就是能够逹到寂空涅槃的究竟法門，可悟不可修。修為成佛，在求。悟為明性，在知。修行以行制性，悟道以性施行，覺者由心生律，修者以律制心。不落惡果者有信無證，住因住果、住念住心，如是生滅。不昧因果者無住而住，無欲無不欲，無戒無不戒，如是涅碦。」


\end{document}
`

this is the test code.

**Comment by abenori** [comment]
I commented out `\setmainjfont { KozMinPr6N-Medium }` because I do not have the font. It again seems fine.
<img width="390" alt="jlreq" src="https://user-images.githubusercontent.com/522782/112450694-fda59f00-8d97-11eb-982f-ad06472c5789.png">

**Comment by asnahu** [comment]
> I commented out `\setmainjfont { KozMinPr6N-Medium }` because I do not have the font. It again seems fine.
> <img alt="jlreq" width="390" src="https://user-images.githubusercontent.com/522782/112450694-fda59f00-8d97-11eb-982f-ad06472c5789.png">

I removed `\setmainjfont` from code, still got the problem.

lualatex version in my computer is: `This is LuaTeX, Version 1.10.0 (TeX Live 2019)`.

**Comment by abenori** [comment]
Mine is `This is LuaHBTeX, Version 1.12.0 (TeX Live 2020/W32TeX)`

I'm doubting that it depends on the viewer. Can you check this with Acrobat Reader?

**Comment by asnahu** [comment]
Found the core of the problem now.  It comes from pdf viewer.  thanks!
