### ISSUE TITLE
pTeX への \ucs 追加に対応

### ISSUE THREAD

**Issue by aminophen** [abenori/jlreq#86]
pTeX 3.10.0 で \ucs プリミティブが追加されました。仕様は https://github.com/texjporg/tex-jp-build/pull/121#issuecomment-870596830 のとおりです。

``` tex
\documentclass{jlreq}
\begin{document}
a
\end{document}
```

```
! LaTeX Error: Font family `JY2+mc' unknown.
```

pLaTeX で上記のエラーが出るようになります。

**Comment by abenori** [comment]
これで大丈夫かしら． 8b34df7 
W32TeXが更新されたら試します．

**Comment by aminophen** [comment]
早速ありがとうございます。pTeX 3.10.0 でも pLaTeX/upLaTeX とも正常判定されました。
