### ISSUE TITLE
LuaLaTeX でタイプセットすると \item コマンドのオプション引数が正しく処理されない

### ISSUE THREAD

**Issue by h20y6m** [abenori/jlreq#87]
最新の jlreq.cls (2021/07/25) を使用すると LuaLaTeX でタイプセットしたときのみ `\item` コマンドのオプション引数が処理されず、そのまま `[]` つきのテキストとして処理されてしまいます。

```LaTeX
\documentclass{jlreq}
\begin{document}
\begin{itemize}
\item[★] ほげ
\item[☆] ふが
\end{itemize}
\begin{description}
\item[ほげ] ほげほげ
\item[ふが] ふがふが
\end{description}
\end{document}
```

LuaLaTeX で処理すると……

![image](https://user-images.githubusercontent.com/57307205/127480944-c61fd8a6-fb9a-4737-8d33-219d900bb8f5.png)

以下の部分で元の `\item` コマンドの**後に**コードを追加しているのが原因ではないかと思います。

https://github.com/abenori/jlreq/blob/133c34ac4798346467ba16e8b519e1fd53735d24/jlreq.cls#L795-L799

**Comment by abenori** [comment]
ありがとうございます．`\item`のオプション引数をすっかり忘れていました． 636073a で直しました．

**Comment by h20y6m** [comment]
ありがとうございます。2021/07/30  で修正されていることを確認しました。
