### ISSUE TITLE
itemizeのbulletが中央からずれる

### ISSUE THREAD

**Issue by okumuralab** [abenori/jlreq#88]
（まちがえたので↓参照）

**Comment by okumuralab** [comment]
縦書きのitemizeのbulletが左にずれているように見えます。

![itemize](https://user-images.githubusercontent.com/3616498/128441719-7895f75e-b13e-447e-ace9-d7695bf1c609.png)

```
\documentclass[tate]{jlreq}
\begin{document}

□□□□
\begin{itemize}
\item □□
\item □□
\end{itemize}
□□□□

\end{document}
```

**Comment by abenori** [comment]
`\textbullet`が左にずれているように見えます．こういうものでしたっけ？

```
\documentclass{tarticle}
\begin{document}
あ\textbullet あ
\end{document}
```
![image](https://user-images.githubusercontent.com/522782/128458124-849e74bb-c5cd-457a-8105-a8fdaf651a14.png)

**Comment by okumuralab** [comment]
縦中横にすれば左右中央に来るんですが。

![bullet](https://user-images.githubusercontent.com/3616498/128460442-7ca76caa-934f-4927-b224-713eae13538f.png)

```
\documentclass[tate]{jlreq}
\begin{document}

□□\textbullet □□

□□\tatechuyoko{\textbullet}□□

\end{document}
```

**Comment by abenori** [comment]
縦幅違うの何でだろう？

**Comment by okumuralab** [comment]
```
\fboxsep=0pt
\fbox{\textbullet}
```

でわかるように，高さより横幅が広いから？

**Comment by okumuralab** [comment]
`\textbullet` の代わりに `\tatechuyoko{\textbullet}` としたりして試してみましたが，結局

```
%\newcommand{\labelitemi}{•}
```

を生かすのがいいように思えてきました。

**Comment by abenori** [comment]
変わらなくないですか？

**Comment by abenori** [comment]
だんだん横書きも気になってきた（これはjsclassesも同じですが）のですがどうなんでしょうか？

```
\documentclass{jlreq}
\begin{document}
\begin{itemize}
\item □□□
\end{itemize}
\end{document}
```

![tex](https://user-images.githubusercontent.com/522782/128587930-5a6857c4-4031-4dd8-93fc-367fbfeb433e.png)

**Comment by okumuralab** [comment]
美文書p.52

![image](https://user-images.githubusercontent.com/3616498/128588291-e04615f9-4311-4a8a-b848-ca6043184705.png)

**Comment by abenori** [comment]
横書きも気になり出すと気になって来ちゃいました．今更ですが．

```
%#!platex --kanji=utf8 --no-guess-input-enc
\documentclass{jlreq}
\renewcommand{\labelitemi}{•}
\begin{document}
\begin{itemize}
\item □□□
\end{itemize}
\end{document}
```

![tex](https://user-images.githubusercontent.com/522782/128588322-dec90e7c-ecf8-46df-ac8f-0eb46217130b.png)

**Comment by okumuralab** [comment]
ほんとだ！ platexだと沈みますね。lualatexでやっていたので気づかなかった。

**Comment by okumuralab** [comment]
U+2022 BULLET が全角か欧文かはエンジンによって違う？

**Comment by abenori** [comment]
確かに欧文扱いにしたらlualatexでもずれました．

```
%#!lualatex
\documentclass{jlreq}
\ltjsetparameter{jacharrange={-1, +2, +3, -4, -5, +6, +7, -8, -9}}
\renewcommand{\labelitemi}{\hbox to 1\zw{\hss •\hss}}
\begin{document}
\begin{itemize}
\item □□□
\end{itemize}
\end{document}
```
![tex](https://user-images.githubusercontent.com/522782/128588692-68d1d11e-d61d-471d-91d0-06a8cfa03b80.png)

うーん，とりあえず`\tatechuyoko`で`\textbullet`を囲むので手をうちましょうか．lualatexならば`\newcommand{\labelitemi}{•}`の方がよさそうですが，エンジンごとに明らかに結果が変わるのもなぁという気がするので．

**Comment by okumuralab** [comment]
ですねー。あまり良い考えが浮かびません。

**Comment by abenori** [comment]
とりあえずそうしてみました． 8c40569 よりよさそうなのが見つかったら教えてください．

**Comment by okumuralab** [comment]
ありがとうございます！

**Comment by takotakot** [comment]
横書きの場合はあまり気にならなかったのは、英小文字は下に寄っているものが多く、下にずれても違和感がないというのはあるかもしれません。`opdq` の横あたりに見えるのではないでしょうか。
