### ISSUE TITLE
別行見出しが改ページされる

### ISSUE THREAD

**Issue by ogawasia** [abenori/jlreq#89]

**Comment by ogawasia** [comment]
間違えました、改めまして
lualatexで下記コードをタイプセット
[untitled.txt](https://github.com/abenori/jlreq/files/7207288/untitled.txt)
見出しと18番の行までが１ページに収まるはずが見出しが改ページされます。
![3](https://user-images.githubusercontent.com/91168489/134272889-26bc5618-62d3-44b2-a2a7-e5b868082334.png)

**Comment by ogawasia** [comment]
18番の行末に\parを付与すると期待通りの結果になりますが、本来\parが入る場所ではないのでどうしたものでしょう。
![4](https://user-images.githubusercontent.com/91168489/134273340-f5c8fe80-1988-40ba-8d3d-e5600c29a6c7.png)

**Comment by ogawasia** [comment]
偶数ページで同様の位置に見出しを配置した場合、`allowbreak_if_evenpage=true` を指定している場合は、見出しの後で改ページされます。しかし、本来は見出しの後に１行分の余地があるはずなのです。
また、奇数ページ同様に18番の行末に`\par`を付与すると見出しの後に１行出力されます。
![5](https://user-images.githubusercontent.com/91168489/134285431-30935425-8a0f-4135-96f0-8336060fb0dd.png)

**Comment by abenori** [comment]
LaTeXの見出しは，その直後の段落の一行目のみを残して改ページするのを避ける仕様になっていますので，そのためかと思います．（`\@afterheading`内で`\clubpenalty`が設定されている．）articleクラスでも以下のような現象が見られます．

```
\documentclass{article}
\usepackage[textheight=70pt,textwidth=50pt]{geometry}
\parindent=0pt
\begin{document}
A B C D E
\section{s}
A B C D E\par% このあるなしで改ページ位置が変わる
A B C D E
A B C D E
\end{document}
```

**Comment by ogawasia** [comment]
LaTexの仕様だったのですね。
お忙しいところありがとうございました。
