### ISSUE TITLE
クラスオプションjlreq_warningsの名称をjlreq_notesに

### ISSUE THREAD

**Issue by yuw** [abenori/jlreq#9]
クラスオプションjlreq_warningsはjlreq_notesの方がよいのではないかという提案です．
また，出てくる(JLReq warning)も(JLReq note)の方がよいのではないでしょうか．

JLReq自身が要求仕様にすぎないということもあり，基準あるいは仕様に反しているような記述はふさわしくないと思います．
もっとも，JLReqの注は要求仕様の範囲を越えているように思える記述が散見されはしますが．

**Comment by abenori** [comment]
いわれてみるとwarningはあまりよくない気もします．notesでいいかな．（他にもっといい単語があれば是非．）
（要求だしrequireで……と思ったらJLReqのReqがRequirementsだったことを思い出しました．）

**Comment by yuw** [comment]
ちなみに，noteを挙げたのは単にJLReqの英訳で注がnoteになっているからです．
“要求”は，組版者に対する要求ではなくてソフトウェア（今はjlreq.cls）設計者／作成者に対するものなので，まぁrequireは重複もしますしあんまりよくないかと思います．

…となるとLaTeXの機能で``Class jlreq Warning:``と出るのも変えた方がよいようなという気もしてきましたが，これ面倒なんでしたっけ？

**Comment by abenori** [comment]
noteだと，「JLReqからの注意！」みたいな気分ですかね．

> LaTeXの機能でClass jlreq Warning:と出るのも変えた方がよいようなという気もしてきました

これなんでですか？

**Comment by yuw** [comment]
> これなんでですか？

Warningって強い言葉なので，“変なことをしている”という誤解を与えそうな気配がしまして．
単なる記号としてあまり気にされないような気もしますが．

**Comment by abenori** [comment]
あ，jlreq_warningsの出力に\ClassWarningNoLine使っていたんでした，忘れていました．warningsをやめるならば普通の方がよさそうですね．

    JLReq notes: ****

みたいな感じでしょうか．

**Comment by yuw** [comment]
おー そうなるといい感じかと思います

**Comment by abenori** [comment]
「note」が適切かどうか微妙に悩んでいるくらいですね．最適な気もしていますが．

**Comment by yuw** [comment]
noteでないとすると… memoくらいでしょうか．

**Comment by abenori** [comment]
noteでいい気がしてきたので変更してみました．
