### ISSUE TITLE
要望：割注前後の括弧の有無を指定したい

### ISSUE THREAD

**Issue by ogawasia** [abenori/jlreq#93]
割注を括弧で囲みたくない場合があるのですが、括弧の有無を指定できると助かります。

**Comment by abenori** [comment]
「日本語組版処理の要件」3.4.2のNOTEにも

> 割注を始め括弧類（cl-01）及び終わり括弧類（cl-02）でくくらずに，指定された一定の空き量をとる方法もある．

とありますね．何かしらカスタマイズ手段を用意するようにします．

**Comment by ogawasia** [comment]
よろしくお願いします

**Comment by abenori** [comment]
902390d で`\jlreqsetup`に`warichu_pre`と`warichu_post`を入れました．`\jlreqsetup{warichu_pre={},warichu_post={}}`とすると括弧が消えるはずです．空白が欲しい場合は適当に空白出力命令を入れてください．`warichu_pre`と`warichu_post`という名前はリリースまでに変更するかもしれません．

**Comment by ogawasia** [comment]
`\jlreqsetup{warichu_pre={},warichu_post={}}` で括弧が消えることを確認しました。
ありがとうございます。
