### ISSUE TITLE
texlive最新版でエラー発生

### ISSUE THREAD

**Issue by johshitak** [abenori/jlreq#94]
縦書きでも横書きでも、長らく使用させていただいております。ありがとうございます。

# 概要

先日更新された60947版にアップデートしたところ、一部のtexファイルで文書作成ができなくなりました。こちらのミスも考えましたが、以前の60713版に戻すと使用することができ、またエラーメッセージがjlreq*.styに関するエラーであるかのように読めました。そのため見当がつかず、お伺いします。

こちらの環境は、以下の通りです。

```
macOS 12.0.1
texlive 2021 本記事投稿時点で最新版にupdate
```

# 詳細

上記の通り、先日jlreqが更新された60947版を取り込んだ後に、一部のtexファイルで文書作成ができなくなりました。以下の通り検証用コード（test.tex）を作成しましたが、60947版ではエラーで文書作成ができません。ただ、60713にリストアするとエラーが発生せずに文書作成が可能です。

```
\documentclass[
  lualatex,
	paper=a4,
	article,
]{jlreq}

\usepackage[no-math]{fontspec}
\usepackage[
  deluxe,
  multi,
  haranoaji,
]{luatexja-preset}
\usepackage{luatexja-otf}
\usepackage{bxjalipsum}

\begin{document}

\jalipsum{iroha}

\end{document}
```

60947版をインストールした状態で発生するエラーは以下の通りです。

```
$ lualatex test.tex

This is LuaHBTeX, Version 1.13.2 (TeX Live 2021) 
 restricted system commands enabled.
(./test-jlreq-60947.tex
LaTeX2e <2021-11-15>
 L3 programming layer <2021-11-12>
(/usr/local/texlive/2021/texmf-dist/tex/latex/jlreq/jlreq.cls
Document Class: jlreq 2021/11/05 jlreq
(/usr/local/texlive/2021/texmf-dist/tex/latex/l3packages/l3keys2e/l3keys2e.sty
(/usr/local/texlive/2021/texmf-dist/tex/latex/l3kernel/expl3.sty
(/usr/local/texlive/2021/texmf-dist/tex/latex/l3backend/l3backend-luatex.def)))
 (/usr/local/texlive/2021/texmf-dist/tex/latex/etoolbox/etoolbox.sty)
(./jlreq-helpers.sty
(/usr/local/texlive/2021/texmf-dist/tex/latex/xkeyval/xkeyval.sty
(/usr/local/texlive/2021/texmf-dist/tex/generic/xkeyval/xkeyval.tex
(/usr/local/texlive/2021/texmf-dist/tex/generic/xkeyval/xkvutils.tex
(/usr/local/texlive/2021/texmf-dist/tex/generic/xkeyval/keyval.tex)))))
! Use of \??? doesn't match its definition.
<argument> \???  
      ! LaTeX3 Error: Erroneous variable \jlreq@helper@papersizelist@a0paper us
l.174 \__jlreq_addpapersize:nnn{a0paper}{}{a0paper}
```

お分かりになることがあればご教示いただけましたら幸いです。

**Comment by abenori** [comment]
手元で最新版にして試してみましたが，エラーなく通ってしまいました．あれれ．
エラーメッセージもよくわからないですね．`\???`って何……？

**Comment by munepi** [comment]
手元のjlreqが `$ tlmgr info jlreq | grep -e 'revision'` が `revision:    60947` となっている下で、同LaTeX文章をタイプセットいたしましたが、問題ありませんでした。

ところで、上記のlog中で、

```
(./jlreq-helpers.sty
```

となっているところが気になります。
通常、distro-wide側の `jlreq-helpers.sty` を読むはずで、

```
(/usr/local/texlive/2021/texmf-dist/tex/latex/jlreq/jlreq-helpers.sty
```

となるべきところです。
同LaTeX文章ファイル test.tex 直下のディレクトリに、余計な localな jlreq-helpers.sty が存在しませんでしょうか？

**Comment by johshitak** [comment]
@abenori 様、@munepi 様

ご返信ありがとうございます。まさしく@munepi様おっしゃるとおりで、test.texと同じフォルダに2018/08/15版のjlreq-helpers.styがあり、こちらの影響だったようです。移動させたら問題なく文書作成することができました。

今となってはなぜこのファイルをここに入れていたのか分からないのですが、府中でお手数をおかけして済みませんでした。重々御礼申し上げます。

**Comment by abenori** [comment]
あ，よかったです．@munepi さんありがとうございます．

**Comment by minamotorin** [comment]
`\RequirePackage{jlreq-helpers}[2021/08/12]`のようなことをしてみませんか。
