### ISSUE TITLE
Open bracket position in list environment

### ISSUE THREAD

**Issue by minamotorin** [abenori/jlreq#96]
# About

1. In LuaLaTeX, open bracket position after label in `list` environment is incorrect.

~2. A position of open bracket at the beginning of label of `itemize` environment also seems to be wrong (even in (u)pLaTeX).~

I've only tested with the `open_bracket_pos=zenkaku_tentsuki`.

# Environments

- LuaHBTeX: 1.13.2
- LaTeX2e: 2021-11-15
- jlreq: 2021/11/05 (1284baa)

# Open bracket position after label

Sample code:

```latex
% This program is in the public domain.
\documentclass[line_length=41zw]{jlreq}
\begin{document}

（□□□□
（□□□□
（□□□□
（□□□□
（□□□□
（□□□□
（□□□□
（□□□□
（□□□□
（□□□□
（□□□□
（□□□□

\noindent
□□□□□

\begin{itemize}
  \item （□□□□
  \item □□□□□
  \item[（□□□□]
  \item[□□□□□]
\end{itemize}

\end{document}
```

When compiling the above code with…

## LuaLaTeX

  ![LuaLaTeX](https://user-images.githubusercontent.com/76122224/143771123-d2f61479-4ac4-4cf2-8f1f-45e4297366a6.jpeg)

## pLaTeX

  ![pLaTeX](https://user-images.githubusercontent.com/76122224/143771139-4fd8cd95-30c5-4f7a-b247-015474bceae0.jpeg)

## Related to #87?

https://github.com/abenori/jlreq/blob/1284baa26eb5bfb0778d9f56312b3b52d1a9a7c4/jlreq.cls#L892-L902

### LuaLaTeX with jlreq 2021/05/28 (3a7010f)

  ![3a7010f](https://user-images.githubusercontent.com/76122224/143771205-973c9a7e-78d3-4aad-8491-4a0eff364a38.jpeg)

### LuaLaTeX with jlreq 2021/05/28 (669b1de)

  ![669b1de](https://user-images.githubusercontent.com/76122224/143771247-b9c3f26a-1a94-47ea-9be0-e265cbb42cef.jpeg)

### LuaLaTeX with jlreq 2021/07/25 (636073a)

![ 636073a](https://user-images.githubusercontent.com/76122224/143771334-c80a3522-d06a-4956-b836-a02b79268113.jpeg)

# ~Open bracket position of label~

~Sample code:~

```latex
% This program is in the public domain.
\documentclass{jlreq}
\begin{document}

\begin{description}
  \item[（□□□□]
  \item[□□□□□]
\end{description}

\begin{itemize}
  \item[（□□□□]
  \item[□□□□□]
\end{itemize}

\end{document}
```

~Open bracket position are difference between `description` environment and `itemize` environment.~

![label](https://user-images.githubusercontent.com/76122224/143773043-b77e0e79-7afe-4566-8829-bce16e0150d2.jpeg)

My all images of this issue are [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

Thanks.

**Comment by minamotorin** [comment]
Sorry, the cause of 2 was the label of `itemize` environment was right justified.

**Comment by abenori** [comment]
Thank you. I merged your pull request.

**Comment by minamotorin** [comment]
Thanks so much!
