### ISSUE TITLE
\expandafter immediately after \tatechuyoko

### ISSUE THREAD

**Issue by minamotorin** [abenori/jlreq#99]
When I was writing a macro, I realized that the following code causes `! Argument of \@secondoftwo has an extra }.` with latest jlreq (4b760c7).

```latex
% This program is in the public domain.
\documentclass[tate]{jlreq}
\begin{document}
\tatechuyoko{A}\expandafter BC
\end{document}
```

I don't know if it's correct and why the following patch solves the issue, but the patch works.

```diff
# This patch is in the public domain.
diff --git a/jlreq.cls b/jlreq.cls
index 9a7d5b1..bc4adb5 100644
--- a/jlreq.cls
+++ b/jlreq.cls
@@ -500,7 +500,7 @@
 
 % #1の先頭が文字か
 \long\def\jlreq@ifletter#1{%
-  \jlreq@iffirsttoken{#1}{ }{\@secondoftwo}{%
+  \jlreq@iffirsttoken{#1}{~}{\@secondoftwo}{%
     \expandafter\expandafter\expandafter\jlreq@helper@ifletter\jlreq@getfirsttoken#1\jlreq@uniqtoken{}\jlreq@endmark@
   }%
 }
```

This error doesn't occur in jlreq up to a4c1608.

Category code of ` ` where `\jlreq@ifletter` is defined changed in a commit 4628414, the commit after a4c1608, because of scope of expl3 syntax.
However, ` ` in `\jlreq@ifletter` was not replaced by `~`.

Thanks.

**Comment by abenori** [comment]
Thanks! You are completely right.  I used your correction. c903cce

**Comment by minamotorin** [comment]
In LuaLaTeX, `\xkanjiskip` is inserted before `　`. This is different from (u)pLaTeX.

```latex
% This program is in the public domain.
\documentclass{jlreq}
\begin{document}

aaaa\　□□

□□□\　aaa

aaaa　□□% <- This

aaaa□□□

□□□　aaa

□□□□aaa

\ifx\undefined\directlua\else
  \catcode`\　=12

  aaaa　□□

  aaaa□□□

  □□□　aaa

  □□□□aaa

\fi

\end{document}
```

- pLaTeX (same as upLaTeX)

  ![(u)p](https://user-images.githubusercontent.com/76122224/145055138-214e0720-5902-423b-8d16-7a103bbf07d5.jpeg)

- LuaLaTeX

  ![lua](https://user-images.githubusercontent.com/76122224/145055276-e42aaefe-44a6-4550-9f44-08c98898ada3.jpeg)

**Comment by minamotorin** [comment]
Inserting of `\xkanjiskip` before `　` only happens when using jfm-jlreq.lua of 3a7010fbd8e07 or later.
I have no idea what is wrong.

**Comment by abenori** [comment]
I added `kanjiskip_natural = 1` to jfm-jlreq.lua which means that kanjiskip added to the glue between characters between `　` and `alchar` (here, `alchar` means non-Japanese character). But xkanjiskip is inserted. I don't know this is expected or not.

**Comment by abenori** [comment]
> I added `kanjiskip_natural = 1` to jfm-jlreq.lua which means that kanjiskip added to the glue between characters between `　` and `alchar` (here, `alchar` means non-Japanese character). But xkanjiskip is inserted. I don't know this is expected or not.

See https://osdn.net/projects/luatex-ja/ticket/43512

**Comment by minamotorin** [comment]
After updating luatexja to 20220103.0, inserting of xkanjiskip before `　` doesn't occur. Thanks!

About Japanese Ghost, I'll ask in [wtsnjp/BXghost](https://github.com/wtsnjp/BXghost).
